### ISSUE TITLE
New provider MangaBat

### ISSUE THREAD

**Issue by gromenauer** [yuru-yuri/manga-dl#100]
New provider proposal `mangabat.com`
Example url: 
`https://mangabat.com/manga/isekai_de_kojiin_wo_hiraitakedo_nazeka_darehitori_sudatou_to_shinai_ken`

**Comment by 1271** [comment]
Thank you. I'll do it as soon as I'm healed. )

**Comment by 1271** [comment]
Please, check `1.3.21`

**Comment by gromenauer** [comment]
Works Ok in `1.3.21` :+1: 

> I'll do it as soon as I'm healed.

We are grateful for your work, no need for fast response time, `manga-py` allows to find the same manga in various providers. 

Please, don't overwork yourself.
