### ISSUE TITLE
Warning when 0 bit images

### ISSUE THREAD

**Issue by gromenauer** [yuru-yuri/manga-dl#104]
I tried to update `http://www.mangasail.com/content/yari-no-yuusha-no-yarinaoshi-manga` chapters and got (again #98) 0 bit images.

Adding a warning `Warning: 0 bit image downloaded, please check for redirection or broken content` will shorten the time to figure that I need to download from `http://www.mangasail.co/content/yari-no-yuusha-no-yarinaoshi-manga` to solve it.
And could be "problematic" if you believe that it downloaded ok and you discover it's empty when you are offline.

**Comment by 1271** [comment]
A good idea. Wait for the update.

**Comment by gromenauer** [comment]
Tested OK. :+1: 
With manga-py version `1.3.24` it gives a warning for every 0 bit image:
~~~
Warning: 0 bit image downloaded, please check for redirection or broken content
~~~
