### ISSUE TITLE
Can't download from kissmanga

### ISSUE THREAD

**Issue by juh9870** [yuru-yuri/manga-dl#108]
When i'm trying download any manga from kissmana.com it waits 30-40 second and terminate process without any result.

~When i'm trying to download any manga from e-hentai.org it gives HUGE error log that doesn't fit in windows cmd and creates folder for this manga without images.
When i'm trying to download manga from e-hentai.org it says to input login & password, but i can't type anything into console when it request password.~
Fixed in 6bd6bced65ea1c5e6c2073fd21466abf2c738a61

**Comment by juh9870** [comment]
Windows 7 x64
commit #ba0fb3ef894f13ee744056b5b4d926dc3f4f4eee

**Comment by 1271** [comment]
Hello!
Thank you for the issue.
I will check it.

As for the password. It should be so. The symbols will not be displayed in the console, but be sure, this will be read after pressing enter.
You must enter a password and press enter.

**Comment by juh9870** [comment]
Tested exhentai, password input works but then it also gives huge error log.

**Comment by 1271** [comment]
Please, check version `1.3.25`

**Comment by juh9870** [comment]
E-hentai and exhentai are working now. Kissmanga still not working, but now gives error 
![image](https://user-images.githubusercontent.com/15922601/44447627-739a6600-a5f1-11e8-809e-6f5baf01b532.png)

**Comment by 1271** [comment]
Oh. I beg your pardon. I did not see a mistake about kissmanga.
I have not seen such a routing yet. This is fixed.
Thank you!

The usual address of the chapter is as follows:
http://kissmanga.com/Manga/Franken-Fran/Vol-008-Ch-060--Right-And-Left?id=106075

And you found this:
http://kissmanga.com/Manga/Franken-Fran/1?id=17373

Please, check `1.3.26`

**Comment by juh9870** [comment]
Big scarry error log disappeared but it stil doesn't download anything
![image](https://user-images.githubusercontent.com/15922601/44461825-11565b00-a61b-11e8-8666-482683d9f94d.png)
![image](https://user-images.githubusercontent.com/15922601/44461827-1a472c80-a61b-11e8-9ce9-8f64983e4ff2.png)

**Comment by 1271** [comment]
Please show the output:
```bash
~/: node -v
v8.9.4
```

There is a possibility that you have an overdue version of node.

**Comment by juh9870** [comment]
![image](https://user-images.githubusercontent.com/15922601/44466696-9ba5bb80-a629-11e8-8a89-f089a7b2981c.png)

**Comment by 1271** [comment]
Please, try:

```
pip install manga-py==1.3.27a0
```

This is a debug version.
Please send here the information that will be displayed in the console after running manga-py.

**Comment by juh9870** [comment]
![image](https://user-images.githubusercontent.com/15922601/44478426-55128a00-a646-11e8-8e01-a65b16ced4df.png)

**Comment by 1271** [comment]
I do not see errors 😢 
Please, show log for version `1.3.27-alpha.1`

```
pip install manga-py==1.3.27a1
```

**Comment by juh9870** [comment]
![image](https://user-images.githubusercontent.com/15922601/44513420-f987e100-a6c5-11e8-9652-1a604dba183b.png)
![image](https://user-images.githubusercontent.com/15922601/44513442-060c3980-a6c6-11e8-8bca-720bede6f8b3.png)

**Comment by 1271** [comment]
Please, show this:

```python
#!/usr/bin/python

from Crypto.Hash import SHA256
crypt = SHA256.new()
crypt.update(b'test')
crypt.hexdigest()
```

Its worked ?

---

Tell me, do you have an [anaconda](https://www.anaconda.com/download/)?
At the moment, working with [crypt](https://pypi.org/project/pycrypto/) is very problematic in windows.
Anaconda solves most of the problems associated with installing packages.

**Comment by juh9870** [comment]
1: How must i run this code? CMD don't accept it.
2: i will download it and try again

**Comment by 1271** [comment]
1) run `cmd` or `powershell`
2) run `python` into `cmd`
3) run code

or:

1) open notepad (any text editor)
2) put code into notepad
3) save as `filename.py`
4) run this:
4.1) open cmd
4.2) run `python filename.py`

**Comment by 1271** [comment]
1. run `cmd` or `powershell`
2. run `python` into `cmd`
3. run code

or:

1. open notepad (any text editor)
2. put code into notepad
3. save as `filename.py`
4. run this:
4.1. open cmd
4.2. run `python filename.py`

**Comment by juh9870** [comment]
![image](https://user-images.githubusercontent.com/15922601/44575737-5ef6d300-a795-11e8-9091-f5ff7d9a35d4.png)

**Comment by 1271** [comment]
manga-py still does not work for you?

If so, I'll try to help you on the weekend.

**Comment by juh9870** [comment]
Sites other than kissmanga works fine

**Comment by 1271** [comment]
I'll make a version with even more debugging information to understand where you're having an error.

Please, show log for
```
pip install manga-py==1.3.27a2
```

**Comment by gromenauer** [comment]
manga-py version `1.3.24`

Seems OK
~~~ bash
pipenv run manga-py --cbz --zero-fill --rename-pages --no-webp --destination Manga/ http://kissmanga.com/Manga/Slime-Life
100% (11 of 11) |#####################| Elapsed Time: 0:00:03 Time:  0:00:03
100% (4 of 4) |#######################| Elapsed Time: 0:00:02 Time:  0:00:02
100% (4 of 4) |#######################| Elapsed Time: 0:00:01 Time:  0:00:01
100% (4 of 4) |#######################| Elapsed Time: 0:00:01 Time:  0:00:01
100% (4 of 4) |#######################| Elapsed Time: 0:00:01 Time:  0:00:01
100% (4 of 4) |#######################| Elapsed Time: 0:00:01 Time:  0:00:01
100% (6 of 6) |#######################| Elapsed Time: 0:00:02 Time:  0:00:02
100% (7 of 7) |#######################| Elapsed Time: 0:00:02 ETA:  00:00:0                                                                                                                                                                                                          100% (7 of 7) |#######################| Elapsed Time: 0:00:02 Time:  0:00:02
100% (10 of 10) |#####################| Elapsed Time: 0:00:01 Time:  0:00:01
~~~

But I have other configuration.
~~~
uname -a
Linux machine 4.4.0-134-generic #160-Ubuntu SMP Wed Aug 15 14:58:00 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

python -V
Python 2.7.12

node -v
v4.2.6
~~~

**Comment by juh9870** [comment]
![image](https://user-images.githubusercontent.com/15922601/44616046-421fd580-a851-11e8-8ff7-1174bfe30e9b.png)
![image](https://user-images.githubusercontent.com/15922601/44616048-477d2000-a851-11e8-90e1-31aca7101940.png)

**Comment by juh9870** [comment]
Alpha 3 shows huge error log and download archive with this content 
![image](https://user-images.githubusercontent.com/15922601/44617973-f7648480-a875-11e8-8088-c8b888a7e56b.png)

Error log:
![image](https://user-images.githubusercontent.com/15922601/44617968-e287f100-a875-11e8-961a-d27697cf5005.png)

**Comment by 1271** [comment]
This should help!

Thank you for your patience

**Comment by juh9870** [comment]
Yeah, now it works, tsx, sorry if my english were bad.
