### ISSUE TITLE
No download in fanfox.net

### ISSUE THREAD

**Issue by gromenauer** [yuru-yuri/manga-dl#112]
manga-py version `1.3.26`

~~~
mkdir /tmp/test
manga-py --cbz --zero-fill --rename-pages --no-webp --destination /tmp/test http://fanfox.net/manga/aura_from_another_planet/
~~~

nothing happens

**Comment by 1271** [comment]
`The series Aura from Another Planet has been licensed, it is not available in Manga Fox`

I added a message stating that the files were not found.

**Comment by gromenauer** [comment]
manga-py version `1.3.27`

Seems that something is not working, when launched the same command:
* No messages
* 99 files containing only `info.txt`

**Comment by 1271** [comment]
Please, check `1.3.28`.
This should work well.

**Comment by gromenauer** [comment]
Works as expected on manga-py version `1.3.28` :+1:
