### ISSUE TITLE
Add acomics.ru

### ISSUE THREAD

**Issue by juh9870** [yuru-yuri/manga-dl#113]
Хотелось бы увидеть в списке поддерживаемых сайтов acomics.ru
В этом сайте нет деления на тома так что думаю просто загружать постранично и аргументы указывающие на скачиваемые тома вместо этого указывают на скачиваемые страницы.

**Comment by 1271** [comment]
This will be added.
But please write in English whenever possible.

---

Это будет добавлено.
Но пожалуйста пишите на английском по возможности.

**Comment by juh9870** [comment]
Hmm, i runned pip install --upgrade manga-py and it installed 1.3.28, but look like this version doesn't have acomics.ru implemented

**Comment by 1271** [comment]
I'm enable it.
Check for version `1.3.29`, please.

**Comment by juh9870** [comment]
Testet it a bit, found some issues.
1: If you downloaded part of comics using -c X then you can't download remaining part untill you delete or rename archive.zip
2: When trying to download comics that protected from downloading it shos error, i think it's better notify user that this comics is protected by site. Example comics: https://acomics.ru/~Oglaf

**Comment by 1271** [comment]
1) Use `--rewrite-exists-archives` ^_^
2) I will check it

**Comment by 1271** [comment]
Sorry for the long wait. Done! Check updates.

P.S. https://acomics.ru/~romac it's very cool comics ^_^

**Comment by juh9870** [comment]
Yeah, it works now.
Romac looks interesting, tsx.
