### ISSUE TITLE
mangarock in reverse order

### ISSUE THREAD

**Issue by gromenauer** [yuru-yuri/manga-dl#115]
Tried with manga-py version `1.3.26`:

~~~ bash
pipenv run manga-py --cbz --zero-fill --rename-pages --no-webp --destination Manga/ https://mangarock.com/manga/mrs-serie-213762
~~~

Downloads OK but it names it as:

1. vol_002-0.cbz
2. vol_001-0.cbz
3. vol_000-0.cbz

When you start at `vol_000-0.cbz` you read the last chapter :warning:

**Comment by gromenauer** [comment]
The same with `manga-py` version `1.3.29.1`

**Comment by 1271** [comment]
Will be fixed in the next version. Thank you.

**Comment by gromenauer** [comment]
Works OK with `manga-py` version `1.3.30` :+1:
