### ISSUE TITLE
[REQUEST] Improve Renaming

### ISSUE THREAD

**Issue by c0fe** [yuru-yuri/manga-dl#117]
I would like to suggest improving the renaming. Currently the renaming is not very helpful:

`vol_000-0`

I would suggest having one:

`[**NAME OF MANGA** ] - VOL. [**#**] - CH. [**#**].cbz`

**Comment by 1271** [comment]
You always have a folder in which the chapters are located.

Unfortunately, not all sites allow you to do so.
For example, sometimes there are chapters of this content:

Volume 4 Chapter 33.4

And sometimes it is not addressed in any way. Only hash-url for page.

But I'll try.
Keep for updates.

**Comment by c0fe** [comment]
@1271 What about scrapping the text of the URL links themselves and not the URL itself?

**Comment by 1271** [comment]
Clarify please.
English is not my native language. )

**Comment by c0fe** [comment]
I am suggesting grabbing the name not from the URL itself but from the hyperlink.

**Comment by 1271** [comment]
Sorry, I do not have access to the page where you received the link.
I can not know what name the hyperlink had.
Some providers use the manga title as the folder name. This will be used in manga-py version 2.
I'm sorry, but changing all providers is not profitable now.
Please use version 2 when it is released.
Planned time of release - the beginning of 2019.

**Comment by c0fe** [comment]
@1271 I was referring to kissmanga and mangarock, those are the only two reliable sites I have been. I figure mangadex could be good too.

The links to the manga have all the information there.

On an unrelated note, can manga-py put this into a pdf format instead of a cbz one?

**Comment by 1271** [comment]
_pdf_?  Yes it is possible.

_I was referring to kissmanga and mangarock_ (,-_-)
You did not indicate this in the message.
https://github.com/yuru-yuri/manga-dl/issues/117#issue-358781729

Please wait for the new version of manga-py.
In this update, the ability to change the name of the archive will be added.
If you still need pdf support, please make a separate issue.
I would not want to mix a few things together.

Thank you for using manga-py.

**Comment by c0fe** [comment]
@1271 I am building manga-py directly from GitHub, just an FYI.

Please add support for MangaDex for proper renaming as it has higher quality releases.

**Comment by 1271** [comment]
Check version 1.3.30.3 please.

**Comment by c0fe** [comment]
@1271 I will check this out, I have been out sick for a little bit but I will check over the weekend and post the results here.

**Comment by 1271** [comment]
Do not hurry. Thanks for your work.
I hope you'll get better soon!

**Comment by 1271** [comment]
I close it because there is no feedback from you.
If you have any questions, click the **reopen** button below.
