### ISSUE TITLE
Bug: https://mangadex.org Provider not found

### ISSUE THREAD

**Issue by gromenauer** [yuru-yuri/manga-dl#118]
Environment (please complete the following information):

Q | A
---|---
OS | Ubuntu 16.04.5 LTS
Python version | Python 2.7.12
Pip version | pip 18.0 
Manga-py version | 1.3.30
npm version | 3.5.2
URL | https://mangadex.org/title/17897/hataraku-saibou

#### To Reproduce:
~~~ bash
pipenv run manga-py --cbz --zero-fill --rename-pages --no-webp --destination Manga/ https://mangadex.org/title/17897/hataraku-saibou
~~~
#### Additional context
Output:
```
Provider not found
Please check the domain in the table: https://manga-dl.yuru-yuri.sttv.me
Make sure that the URL is correct
...
```
Checking the domain in the table: https://manga-dl.yuru-yuri.sttv.me I see
```
http://mangadex.com
http://mangadex.org 
```
Tried with `http` in `.com` and `.org` with no luck

**Comment by 1271** [comment]
They probably changed the routing.
Thank you.

**Comment by 1271** [comment]
Please, check [v1.3.30.2](https://github.com/yuru-yuri/manga-dl/releases/tag/1.3.30.2)

**Comment by gromenauer** [comment]
Works OK :+1: 

Component | Value
---|---
OS | Ubuntu 16.04.5 LTS
Python version | Python 3.5.2
Pip version | pip 18.0 
Manga-py version | 1.3.30.3
URL | `https://mangadex.org/title/17897/hataraku-saibou`

it gets: 
~~~
vol1-ch-1-English.cbz
vol1-ch-1-Portuguese(Br).cbz
vol1-ch-1-Russian.cbz
vol1-ch-2-Portuguese(Br).cbz
vol1-ch-2-Russian.cbz
vol1-ch-3-Portuguese(Br).cbz
vol1-ch-3-Russian.cbz
vol1-ch-4-Portuguese(Br).cbz
vol1-ch-4-Russian.cbz
vol2-ch-5-Portuguese(Br).cbz
vol2-ch-5-Russian.cbz
vol2-ch-6-Portuguese(Br).cbz
vol2-ch-7-Portuguese(Br).cbz
vol2-ch-8-Portuguese(Br).cbz
vol2-ch-9-Portuguese(Br).cbz
~~~

How could I get only the `*English*` files?

**Comment by 1271** [comment]
@gromenauer, i did it!
Check version `1.3.30.5`

**Comment by gromenauer** [comment]
Works ok :+1: 

Component | Value
---|---
OS | Ubuntu 16.04.5 LTS
Python version | Python 3.5.2
Pip version | pip 18.0 
Manga-py version | 1.3.30.5
URL | `https://mangadex.org/title/17897/hataraku-saibou`

**Comment by gromenauer** [comment]
As it is now it's good enough for the normal use case.
If you want to use it in a script that goes into every comic downloading the new chapters... I could use it too.
I feel that should be a better way, but I can't see it (As a parameter should be more complicated). 

Just thinking out loud.

**Comment by 1271** [comment]
For scripts:

```bash
for i in 'http://manga1, http://manga2' do; echo 'en' | manga-py "$i"; done
```
This should work)
