### ISSUE TITLE
How to use the Manga DL

### ISSUE THREAD

**Issue by ryanpaik2002** [yuru-yuri/manga-dl#120]
Hi, I was just reaching out because I was struggling to use the manga dl. I'm sorry I'm inexperienced but how do I operate this program? Thank you so much and sorry for the inconvenience

I tried to input this:
`manga-py https://manganelo.com/manga/read_one_punch_man_manga_online_free3
`
but I'm constantly getting:
  ```
File "/anaconda3/lib/python3.6/site-packages/manga_py/fs.py", line 44, in remove_file_query_params
    file_path = dirname(name)
  File "/anaconda3/lib/python3.6/site-packages/manga_py/fs.py", line 67, in dirname
    return str(Path(_path).parent)
  File "/anaconda3/lib/python3.6/pathlib.py", line 999, in __new__
    self = cls._from_parts(args, init=False)
  File "/anaconda3/lib/python3.6/pathlib.py", line 656, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/anaconda3/lib/python3.6/pathlib.py", line 640, in _parse_args
    a = os.fspath(a)
```

**Comment by gromenauer** [comment]
Tried with the same error:

 Component | Value
---|---
OS | Ubuntu 16.04.5 LTS
Python version | Python 3.5.2
Pip version | pip 18.0 
Manga-py version | 1.3.30.3
URL | `https://manganelo.com/manga/read_one_punch_man_manga_online_free3`

**Comment by 1271** [comment]
Oh. Sorry, I did not check it. Now everything should work fine!
Check `1.30.4`, please!

**Comment by gromenauer** [comment]
Seems OK for me. :+1: 
It have the occasional image fail, but OK.
~~~
Warning: 0 bit image downloaded, please check for redirection or broken content
Broken url: http://s1.mkklcdnv2.com/mangakakalot/r1/read_one_punch_man_manga_online_free3/chapter_15_fun_and_work/2.jpg
Page idx: 2
~~~

Component | Value
---|---
OS | Ubuntu 16.04.5 LTS
Python version | Python 3.5.2
Pip version | pip 18.0 
Manga-py version | 1.3.29.1
URL | `https://manganelo.com/manga/read_one_punch_man_manga_online_free3`

**Comment by 1271** [comment]
You did not check it?
https://github.com/yuru-yuri/manga-dl/issues/118#issuecomment-426169635
If you have suggestions for issue 118/120, I would listen to them.

**Comment by 1271** [comment]
I close it because there is no feedback from you.
If you have any questions, click the **reopen** button below.
