### ISSUE TITLE
Bug in mangabat provider

### ISSUE THREAD

**Issue by gromenauer** [yuru-yuri/manga-dl#122]
# Bug report
Environment (please complete the following information):

Description | Data
---|---
OS | Ubuntu 16.04.5 LTS
Python version | Python 3.5.2
Pip version | pip 18.1 
Manga-py version | 1.3.30.7
URL | `https://mangabat.com/manga/serie-1088913029`

#### To Reproduce:

~~~ bash
pipenv run manga-py --cbz --zero-fill --rename-pages --no-webp --destination Manga/ https://mangabat.com/manga/serie-1088913029
~~~

#### Additional context

Error:
~~~ python
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/provider.py", line 81, in process
    self.loop_chapters()
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/provider.py", line 110, in loop_chapters
    self._info.add_volume(self.chapter_for_json(), self.get_archive_path())
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/provider.py", line 155, in get_archive_path
    _path = remove_file_query_params(self.get_archive_name())
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/providers/helpers/std.py", line 6, in get_archive_name
    idx = self.get_chapter_index()
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/providers/manganelo_com.py", line 9, in get_chapter_index
    return re.search(self.chapter).group(1).replace('.', '-')
~~~

**Comment by 1271** [comment]
Thanks for the issue.
I will fix it soon!

**Comment by gromenauer** [comment]
Half solved, problem with name folder.

Component | Value
---|---
OS | Ubuntu 16.04.5 LTS
Python version | Python 3.5.2
Pip version | pip 18.1 
Manga-py version | 1.3.30.9
URL | `https://mangabat.com/manga/serie-1088913029`

~~~ bash
pipenv run manga-py --cbz --zero-fill --rename-pages --no-webp --destination Manga/ --reverse-downloading --max-volumes 1 https://mangabat.com/manga/serie-1088913029
~~~

Filename output:
~~~
serie-1088913029/vol_010-0.cbz
~~~

Filename is OK but folder name name should be something like:
* `NEET dakedo Hello Work ni Ittara Isekai ni Tsuretekareta/`
* `NEET dakedo HELLO WORK ni ittara isekai ni tsuretekareta/ `

**Comment by 1271** [comment]
> folder name

:D 

The name has always been derived from the url.
Ok, I'll change it.

**Comment by 1271** [comment]
https://pypi.org/project/manga-py/1.3.31rc1/

**Comment by gromenauer** [comment]
Works OK :+1: 

Component | Value
---|---
OS | Ubuntu 16.04.5 LTS
Python version | Python 3.5.2
Pip version | pip 18.1 
Manga-py version | 1.3.31
URL | `https://mangabat.com/manga/serie-1088913029`
Dir Name | NEET dakedo HELLO WORK ni ittara isekai ni tsuretekareta
