### ISSUE TITLE
Bug: Strange chapter naming in mangatown provider

### ISSUE THREAD

**Issue by gromenauer** [yuru-yuri/manga-dl#124]
# Bug report
Environment:

Description | Data
---|---
OS | Ubuntu 16.04.5 LTS
Python version | Python 3.5.2
Pip version | pip 18.1 
Manga-py version | 1.3.30.7
URL | `http://www.mangatown.com/manga/kenja_no_deshi_wo_nanoru_kenja/`
URL | `http://www.mangatown.com/manga/takarakuji_de_40_oku_atattandakedo_isekai_ni_ijuu_suru/`

#### To Reproduce:

~~~ bash
pipenv run manga-py --cbz --zero-fill --rename-pages --no-webp --destination Manga/ \
  --name kenja_no_deshi_wo_nanoru_kenja \
  http://www.mangatown.com/manga/kenja_no_deshi_wo_nanoru_kenja/
~~~

#### Additional context
Listing the downloads I got this strange names:
~~~
vol_000-0-ch_-0-0-1.cbz
vol_000-0-ch_-0-0-2.cbz
vol_000-0-ch_-0-0-3.cbz
...
~~~
Instead of the usual naming:
~~~
vol_001-0.cbz
vol_002-0.cbz
vol_003-0.cbz
...
~~~

**Comment by 1271** [comment]
Thanks for the issue.
I will fix it soon!

**Comment by 1271** [comment]
New __true__ filenames:
vol_000-ch_001

Many thanks for your help!

---
P.S.

Some providers are still not transferred to the new naming system.
I will do this as soon as time appears.
Thank you for your patience!

**Comment by gromenauer** [comment]
Even with the patch it still produces a `-0` in excess

~~~
vol_000-0-ch_023.cbz
       ^^
~~~
Done with:
~~~ bash
pipenv run manga-py --cbz --zero-fill --rename-pages --no-webp --destination Manga/ --reverse-downloading --max-volumes 1 http://www.mangatown.com/manga/kenja_no_deshi_wo_nanoru_kenja/
~~~

Component | Value
---|---
OS | Ubuntu 16.04.5 LTS
Python version | Python 3.5.2
Pip version | pip 18.1 
Manga-py version | 1.3.30.9
URL | `--reverse-downloading --max-volumes 1 http://www.mangatown.com/manga/kenja_no_deshi_wo_nanoru_kenja/`

**Comment by 1271** [comment]
Try removing the --zero-fill option
I changed the name generation logic.
Now it really makes sense.

**Comment by 1271** [comment]
https://pypi.org/project/manga-py/1.3.31rc1/

**Comment by gromenauer** [comment]
Works OK :+1: 

Component | Value
---|---
OS | Ubuntu 16.04.5 LTS
Python version | Python 3.5.2
Pip version | pip 18.1 
Manga-py version | 1.3.31
URL | `http://www.mangatown.com/manga/kenja_no_deshi_wo_nanoru_kenja`
URL | `http://www.mangatown.com/manga/takarakuji_de_40_oku_atattandakedo_isekai_ni_ijuu_suru/`
