### ISSUE TITLE
Redirection mangaid.me

### ISSUE THREAD

**Issue by gromenauer** [yuru-yuri/manga-dl#127]
# Request to add a site

Description | Data
---|---
Url to add | https://mangaid.me/

Is a redirection of :
http://mangaid.co (Gone)
http://mangaid.net (Redirected)

**Comment by 1271** [comment]
Thank. This is added!

**Comment by gromenauer** [comment]
It's a non english site (may be indonesian), just reporting it. Someone may be interested.

**Comment by 1271** [comment]
Oh. Sorry, I did not look at the new site.
They updated the design. I made a separate provider for the site.
Thank!

**Comment by gromenauer** [comment]
It's working OK now :+1: 

Component | Value
---|---
OS | Ubuntu 16.04.5 LTS
Python version | Python 3.5.2
Pip version | pip 18.1 
Manga-py version | 1.3.31.2
URL | `https://mangaid.me/manga/her-summon/`
