### ISSUE TITLE
Error downloading from kissmanga

### ISSUE THREAD

**Issue by juh9870** [yuru-yuri/manga-dl#128]
# Bug report
Description | Data
---|---
OS | Windows 7
Python version | 3.5.2
Pip version | 18.1
Manga-py version | 1.3.31
URL | http://kissmanga.com/Manga/Dengeki-Daisy

# Error log
![image](https://user-images.githubusercontent.com/15922601/47956834-d3c76400-dfb3-11e8-99e1-437c8ae52d1c.png)

**Comment by 1271** [comment]
Oh. They have terrible naming chapters.
Sorry, I will change the generation of the file name for this site.
New name:

<idx>-<site-internal-id>-<full-chapter-name>

Example:
https://kissmanga.com/Manga/Dengeki-Daisy/Dengeki-Daisy-1-Suspicious-Guy?id=4516

Output:

001-4516-Dengeki-Daisy-1-Suspicious-Guy.<ext*>

ext = zip or cbz

**Comment by 1271** [comment]
Oh. They have terrible naming chapters.
Sorry, I will change the generation of the file name for this site.
New name:

<idx>-<site-internal-id>-<full-chapter-name>

Example:
https://kissmanga.com/Manga/Dengeki-Daisy/Dengeki-Daisy-1-Suspicious-Guy?id=4516

Output:

001-4516-Dengeki-Daisy-1-Suspicious-Guy.<ext*>

ext = zip or cbz

**Comment by 1271** [comment]
Check `pip install manga-py -U`

**Comment by juh9870** [comment]
Yeah, all works fine
