### ISSUE TITLE
strange filename in mangadex

### ISSUE THREAD

**Issue by gromenauer** [yuru-yuri/manga-dl#130]
# Bug report

Component | Value
---|---
OS | Ubuntu 16.04.5 LTS
Python version | Python 3.5.2
Pip version | pip 18.1 
Manga-py version | 1.3.31.1
URL | `https://mangadex.org/title/31582/orenchi-ni-kita-onna-kishi-to-inakagurashi-suru-koto-ni-natta-ken`

#### To Reproduce:
~~~ bash
pipenv run manga-py --cbz --zero-fill --rename-pages --no-webp --destination Manga/ https://mangadex.org/title/31582/orenchi-ni-kita-onna-kishi-to-inakagurashi-suru-koto-ni-natta-ken
~~~ 

#### Additional context

Files downloaded:

~~~
-ch_1-English.cbz
~~~

**Comment by 1271** [comment]
The manga was missing a **volume** pointer.
Thank!

**Comment by gromenauer** [comment]
Thanks to you too :medal_sports: 

It's working OK now :+1: 

Component | Value
---|---
OS | Ubuntu 16.04.5 LTS
Python version | Python 3.5.2
Pip version | pip 18.1 
Manga-py version | 1.3.31.2
URL | `https://mangadex.org/title/31582/orenchi-ni-kita-onna-kishi-to-inakagurashi-suru-koto-ni-natta-ken`
