### ISSUE TITLE
Request to add mangafull.org

### ISSUE THREAD

**Issue by gromenauer** [yuru-yuri/manga-dl#131]
# Request to add a site

Description | Data
---|---
Url to add | `http://mangafull.org/`

**Comment by 1271** [comment]
Please, check `1.3.31.3`

**Comment by gromenauer** [comment]
Works OK :+1: 

Component | Value
---|---
OS | Ubuntu 16.04.5 LTS
Python version | Python 3.5.2
Pip version | pip 18.1 
Manga-py version | 1.3.31.3
URL | `http://mangafull.org/manga/let-this-place-be-an-alternate-universe`
