### ISSUE TITLE
No download for fanfox.net 

### ISSUE THREAD

**Issue by gromenauer** [yuru-yuri/manga-dl#133]
# Bug report

Description | Data
---|---
OS | Ubuntu 16.04.5 LTS
Python version | Python 3.5.2
Pip version | pip 18.1 
Manga-py version | 1.3.31.3
URL | `http://fanfox.net/manga/the_hero_is_overpowered_but_overly_cautious/`
URL | `http://fanfox.net/manga/aura_from_another_planet`

#### To Reproduce:
~~~ bash
pipenv run manga-py --cbz --zero-fill --rename-pages --no-webp --destination Manga/ http://fanfox.net/manga/the_hero_is_overpowered_but_overly_cautious/
~~~

#### Additional context

No oputput is displayed.
Could be a regression of  #112?

**Comment by 1271** [comment]
Maybe. Thanks for the issue!

**Comment by gromenauer** [comment]
Tried it, works most of the time :sweat_smile: 

Component | Value
---|---
OS | Ubuntu 16.04.5 LTS
Python version | Python 3.5.2
Pip version | pip 18.1 
Manga-py version | 1.3.32

URL | Result
---|---
`http://fanfox.net/manga/aura_from_another_planet` | OK :+1: 
`http://fanfox.net/manga/the_abandoned_empress/` | OK :+1: 
`http://fanfox.net/manga/isekai_shoukan_sareta_ga_kyousei_soukan_sareta  _ore_ha_shikatanaku_yaseru_koto_ni_shita/`| :bug: Nothing happens
`http://fanfox.net/manga/the_hero_is_overpowered_but_overly_cautious/` | :bug: :boom: Error: `'NoneType' object has no attribute 'group'`

**Comment by 1271** [comment]
Oh ... I'll try.
Sorry. Last time, I am very distracted. (

**Comment by gromenauer** [comment]
Don't be sorry, it works 200% of the time (no fanfox, just try in other provider).
No complains from me then, only bugs :bug:, that are normal part of the business. 
And I think that is pretty bug free for the ton of providers that it have.

**Comment by 1271** [comment]
:-)
Thank. Just coming New Year and the desire to work after work less and less.
I need a vacation!

**Comment by 1271** [comment]
Oh. Sorry for such a long wait.
I did it!
Unfortunately, for a manga with such protection, links are long parsed, but it works well for me.
Please check.
If something doesn't work, please write it down.
Thank you for using manga-py =)

**Comment by gromenauer** [comment]
Component | Value
---|---
OS | Ubuntu 16.04.5 LTS
Python version | Python 3.5.2
Pip version | pip 18.1 
Manga-py version | 1.4.0
URL | `http://fanfox.net/manga/the_abandoned_empress/`



URL | Result
---|---
`http://fanfox.net/manga/aura_from_another_planet` | OK :+1: 
`http://fanfox.net/manga/the_abandoned_empress/` | OK :+1: 
`http://fanfox.net/manga/the_hero_is_overpowered_but_overly_cautious/` | OK :+1: 
`http://fanfox.net/manga/world_customize_creator/`  | OK :+1: 
`http://fanfox.net/manga/isekai_shoukan_sareta_ga_kyousei_soukan_sareta  _ore_ha_shikatanaku_yaseru_koto_ni_shita/`| :bug: No chapter detected/downloaded

**Comment by 1271** [comment]
> http://fanfox.net/manga/isekai_shoukan_sareta_ga_kyousei_soukan_sareta_ore_ha_shikatanaku_yaseru_koto_ni_shita/

Thank. I will check it.

**Comment by 1271** [comment]
The link selector was different for this manga.
Changed to general. Now this should always work.
Thank.

**Comment by gromenauer** [comment]
Works OK :+1: 

Component | Value
---|---
OS | Ubuntu 16.04.5 LTS
Python version | Python 3.5.2
Pip version | pip 18.1 
Manga-py version | 1.5.1
URL | `http://fanfox.net/manga/isekai_shoukan_sareta_ga_kyousei_soukan_sareta_ore_ha_shikatanaku_yaseru_koto_ni_shita/`

**Comment by SehWho** [comment]
It seems that there are still other links that don't work.  The ones mentioned here are fixed for me, but this, for instance, still doesn't work:

`http://fanfox.net/manga/koukaku_kidoutai/`

**Comment by 1271** [comment]
@SehWho
Thank you for your message.
Yes, that doesn't work for me either.
I will try to fix it.
