### ISSUE TITLE
Bug in mangakatana image content

### ISSUE THREAD

**Issue by gromenauer** [yuru-yuri/manga-dl#134]
# Bug report

Description | Data
---|---
OS | Ubuntu 16.04.5 LTS
Python version | Python 3.5.2
Pip version | pip 18.1 
Manga-py version | 1.3.31.3
URL | `http://mangakatana.com/manga/the-hero-is-overpowered-but-overly-cautious.21817`

#### To Reproduce:
~~~ bash
pipenv run manga-py --cbz --zero-fill --rename-pages --no-webp --destination Manga/ http://mangakatana.com/manga/the-hero-is-overpowered-but-overly-cautious.21817
~~~

#### Additional context

All images in the comic are wrong, they have html inside and no extension.

**Comment by 1271** [comment]
in progress now ... )
![2018-12-05-160236_448x506_scrot](https://user-images.githubusercontent.com/1452243/49515204-5be8a400-f8a7-11e8-9357-05a6fcd9927c.png)

**Comment by gromenauer** [comment]
works OK :+1: 

Component | Value
---|---
OS | Ubuntu 16.04.5 LTS
Python version | Python 3.5.2
Pip version | pip 18.1 
Manga-py version | 1.3.32
URL | `http://mangakatana.com/manga/the-hero-is-overpowered-but-overly-cautious.21817`
URL | `http://mangakatana.com/manga/isekai-kenkokuki.19421`
