### ISSUE TITLE
Add nineanime.com provider

### ISSUE THREAD

**Issue by gromenauer** [yuru-yuri/manga-dl#135]
# Request to add a site

Description | Data
---|---
Url to add | `https://www.nineanime.com/`
Example | `https://www.nineanime.com/manga/Kono_Yuusha_ga_Ore_Tueee_Kuse_ni_Shinchou_Sugiru.html`

**Comment by 1271** [comment]
It will hurt.
I do not know how to keep their numbering.
I'll try to keep chapter, but volume ... it's not real.

![2018-12-06-085716_281x425_scrot](https://user-images.githubusercontent.com/1452243/49564625-3f934880-f935-11e8-9780-468ff8190a6f.png)

**Comment by gromenauer** [comment]
Worked OK :+1: 

Yes, this web volume information don't seem to be reliable. Maybe it's better to fix volume to 0.

Component | Value
---|---
OS | Ubuntu 16.04.5 LTS
Python version | Python 3.5.2
Pip version | pip 18.1 
Manga-py version | 1.3.32
URL | `https://www.nineanime.com/manga/Kono_Yuusha_ga_Ore_Tueee_Kuse_ni_Shinchou_Sugiru.html`
