### ISSUE TITLE
Add provider for boredomsociety.xyz

### ISSUE THREAD

**Issue by gromenauer** [yuru-yuri/manga-dl#136]
# Request to add a site

Description | Data
---|---
Url to add | `https://www.boredomsociety.xyz/`
Example | `https://www.boredomsociety.xyz/titles/info/22`

**Comment by 1271** [comment]
Hi. This does not work? Or you have not checked?
Can I close the issue?

**Comment by gromenauer** [comment]
Sorry for the delay, I lost track of it :sweat_smile: 

Works OK :+1: 

Component | Value
---|---
OS | Ubuntu 16.04.5 LTS
Python version | Python 3.5.2
Pip version | pip 18.1 
Manga-py version | 1.4.0
URL | `https://www.boredomsociety.xyz/titles/info/22`
