### ISSUE TITLE
Add support for webtoons.com

### ISSUE THREAD

**Issue by edvinbasil** [yuru-yuri/manga-dl#137]
# Request to add a site

Description | Data
---|---
Url to add | `https://www.webtoons.com/`
Example | `https://www.webtoons.com/en/romance/letsplay/list?title_no=1218`

**Comment by 1271** [comment]
Thanks for the issue.
This will be added soon.

**Comment by 1271** [comment]
Ohh...
This has been added a long time ago.
Please check it here:

https://manga-dl.yuru-yuri.sttv.me/
