### ISSUE TITLE
Bug: chapters missing in mangatown.com provider  

### ISSUE THREAD

**Issue by gromenauer** [yuru-yuri/manga-dl#138]
# Bug report
Environment:

Description | Data
---|---
OS | Ubuntu 16.04.5 LTS
Python version | Python 3.5.2
Pip version | pip 18.1 
Manga-py version | 1.3.32
URL | `http://www.mangatown.com/manga/ragna_crimson/`

#### To Reproduce:
~~~ bash
pipenv run manga-py --cbz --zero-fill --rename-pages --no-webp \
    --destination Manga/ \
    --name ragna_crimson \
    http://www.mangatown.com/manga/ragna_crimson/
~~~
#### Additional context
First three chapters are missing
~~~ bash
$ ls Manga/ragna_crimson
vol_000-ch_004.cbz
vol_000-ch_005.cbz
vol_000-ch_006.cbz
vol_000-ch_007.cbz
vol_000-ch_008.cbz
vol_002-ch_008-1.cbz
vol_002-ch_008-2.cbz
vol_002-ch_009.cbz
vol_002-ch_010.cbz
vol_002-ch_011.cbz
vol_002-ch_012.cbz
vol_002-ch_014.cbz
vol_002-ch_015.cbz
~~~

**Comment by 1271** [comment]
I see:
![default](https://user-images.githubusercontent.com/1452243/50050795-68c28e80-0116-11e9-9ee0-fa05e0415edd.png)

**Comment by gromenauer** [comment]
Ooops! :sweat_smile:
