### ISSUE TITLE
Mangarock Windows 10

### ISSUE THREAD

**Issue by theincognito-inc** [yuru-yuri/manga-dl#139]
# Bug report
Environment (please complete the following information):

Description | Data
---|---
OS | Windows 10
Python version | 3.7.0
Pip version | 18.1
Manga-py version | 1.3.32
URL | https://mangarock.com/manga/mrs-serie-253787

#### To Reproduce:
manga-py --cbz --zero-fill --rename-pages --no-webp --destination Manga/ https://mangarock.com/manga/mrs-serie-253787

#### Additional context
File "c:\program files (x86)\python37-32\lib\site-packages\manga_py\providers\__init__.py", line 789, in get_provider
    provider = __import__('{}.{}'.format(fromlist, i), fromlist=[fromlist])
  File "c:\program files (x86)\python37-32\lib\site-packages\manga_py\providers\mangarock_com.py", line 1, in <module>
    from manga_py.crypt import MangaRockComCrypt
  File "c:\program files (x86)\python37-32\lib\site-packages\manga_py\crypt\__init__.py", line 2, in <module>
    from .base_lib import BaseLib
  File "c:\program files (x86)\python37-32\lib\site-packages\manga_py\crypt\base_lib.py", line 8, in <module>
    from Crypto.Cipher import AES
  File "c:\program files (x86)\python37-32\lib\site-packages\Crypto\Cipher\AES.py", line 50, in <module>
    from Crypto.Cipher import _AES

**Comment by 1271** [comment]
Hi. Tell me, how did you install python?
The best solution for your situation is to install anaconda (https://repo.anaconda.com/archive/Anaconda2-4.4.0-Windows-x86_64.exe)
The fact is that windows experiences difficulties with crypt packages necessary for proper operation of the decoder.

**Comment by theincognito-inc** [comment]
@1271 May I ask why this old Anaconda package? I shouldn't install the latest one?

**Comment by 1271** [comment]
@theincognito-inc 
Yes, you can use the latest version, but this is not being tested now for version python 3.7
(I'm just too lazy :-))
But it should work well.
If you have questions, or you find errors in the work, please do not hesitate to write.
Your help means a lot to me.

Thank )

**Comment by gromenauer** [comment]
Tried to reproduce the bug, but in Linux it's working OK.

Component | Value
---|---
OS | Ubuntu 16.04.5 LTS
Python version | Python 3.5.2
Pip version | pip 18.1 
Manga-py version | 1.4.0
URL | `https://mangarock.com/manga/mrs-serie-253787`

**Comment by theincognito-inc** [comment]
@1271 @gromenauer 
Hi, was busy for the previous days. Uninstalled python completely and installed the latest Anaconda package. Python version - 3.7.0

Command used: `pipenv run manga-py --cbz --zero-fill --rename-pages --no-webp --destination Manga/ https://mangarock.com/manga/mrs-serie-253787`

Result got:
` 97% (46 of 47) |##############################################################  | Elapsed Time: 0:01:27 ETA:   0:00:01
cannot identify image file 'C:\\Users\\AGS\\AppData\\Local\\Temp\\.PyMangaDownloader\\temp_11676\\005.mri'
cannot identify image file 'C:\\Users\\AGS\\AppData\\Local\\Temp\\.PyMangaDownloader\\temp_11676\\005.mri'
100% (47 of 47) |################################################################| Elapsed Time: 0:01:28 Time:  0:01:28
 96% (29 of 30) |#############################################################   | Elapsed Time: 0:00:34 ETA:   0:00:00
cannot identify image file 'C:\\Users\\AGS\\AppData\\Local\\Temp\\.PyMangaDownloader\\temp_11676\\005.mri'
cannot identify image file 'C:\\Users\\AGS\\AppData\\Local\\Temp\\.PyMangaDownloader\\temp_11676\\005.mri'

 96% (25 of 26) |#############################################################   | Elapsed Time: 0:00:28 ETA:   0:00:01
cannot identify image file 'C:\\Users\\xxyyzz\\AppData\\Local\\Temp\\.PyMangaDownloader\\temp_11676\\005.mri'
cannot identify image file 'C:\\Users\\xxyyzz\\AppData\\Local\\Temp\\.PyMangaDownloader\\temp_11676\\005.mri'
100% (26 of 26) |################################################################| Elapsed Time: 0:00:29 Time:  0:00:29
 94% (18 of 19) |############################################################    | Elapsed Time: 0:00:18 ETA:   0:00:00
cannot identify image file 'C:\\Users\\xxyyzz\\AppData\\Local\\Temp\\.PyMangaDownloader\\temp_11676\\005.mri'
cannot identify image file 'C:\\Users\\xxyyzz\\AppData\\Local\\Temp\\.PyMangaDownloader\\temp_11676\\005.mri'
100% (19 of 19) |################################################################| Elapsed Time: 0:00:19 Time:  0:00:19
.
.
.`

Finally,nothing shows up in the folder. Perhaps this is not compatible with the latest Python 3?

**Comment by 1271** [comment]
My ubuntu works fine with python 3.7
Provided that you have not seen errors when installing manga-py, this should work even on python 3.8 =)

I need your help.
You need to go to the folder `C:\Users\xxyyzz\AppData\Local\Temp\.PyMangaDownloader\<temp_dir>` and check whether the files being downloaded are images.
If possible, could you attach the archive with these files to your answer?
I will be very happy if you help me.
Thank!

**Comment by theincognito-inc** [comment]
@1271 

I did try, I can download, but none of the files can be read by any comic book reader I have!
The individual .mri files can be opened by Paint, though.

PFA first archive:
[vol_000-0.zip](https://github.com/yuru-yuri/manga-dl/files/2716277/vol_000-0.zip)
PS: I had to change the extension of the archive to upload here. It was originally in cbz

**Comment by theincognito-inc** [comment]
@1271 Update:

Apparently, my Kali Linux also works fine with Python 3.7. I can download easily from it.
Still, it's not working in Windows 10. I have given up trying to make it work in Windows. I can easily work it in my Kali. 

Thanks a lot! If anything comes up, let me know! Other than that, feel free to close this ticket! :D

**Comment by 1271** [comment]
OK. I'm sorry this does not work in windows for you.
But I'm glad you found a way out of their situation.

**Comment by 1271** [comment]
@theincognito-inc
I am aware that the package for windows is called differently.
However, it never caused problems.
But thanks for that comment. I will consider it.
