### ISSUE TITLE
bug: mangago.me

### ISSUE THREAD

**Issue by paranoid73** [yuru-yuri/manga-dl#141]
# Bug report

Description | Data
---|---
OS |Arch Linux
Python version | 3.7.1
Pipenv  version  | 2018.11.26
Manga-py version | 1.3.32.1
URL | http://www.mangago.me/read-manga/worlds_end_harem/ 

#### To Reproduce:
`pipenv run manga-py http://www.mangago.me/read-manga/worlds_end_harem/ `
#### Additional context
```
[Errno 2] No such file or directory: 'manga_py/crypt/aes.js'
[Errno 2] No such file or directory: 'manga_py/crypt/aes.js'
[Errno 2] No such file or directory: 'manga_py/crypt/aes.js'
...
```

**Comment by 1271** [comment]
Thanks for the issue.
I will check it out.

**Comment by 1271** [comment]
Check `1.4.0` after 10 minutes.

**Comment by paranoid73** [comment]
I just update 
![2018-12-24_06 50 55](https://user-images.githubusercontent.com/34898251/50392728-95932900-0748-11e9-9151-7065e162a991.png)
and i still get : 
```
▶ pipenv run manga-py http://www.mangago.me/read-manga/worlds_end_harem/
[Errno 2] No such file or directory: 'manga_py/crypt/aes.js'
[Errno 2] No such file or directory: 'manga_py/crypt/aes.js'
```

**Comment by 1271** [comment]
Hmmm...

OK. I need a little more time.
I will fix this after my work.

**Comment by 1271** [comment]
Looks like the site has changed encryption.
I will leave this issue open and will try to fix it soon.

**Comment by 1271** [comment]
Looks like the site has changed encryption.
I will leave this issue open and will try to fix it soon.

**Comment by 1271** [comment]
mangago will be temporarily excluded from the list of supported resources until I find a lot of time to update the protection script.
Sorry.
