### ISSUE TITLE
add support for manhwahentai.com

### ISSUE THREAD

**Issue by paranoid73** [yuru-yuri/manga-dl#142]
# Request to add a site

Description | Data
---|---
Url to add | https://manhwahentai.com/
Example | https://manhwahentai.com/manhwa/healing-hands-obgyn/

**Comment by 1271** [comment]
Please, check update.
It works now.

**Comment by gromenauer** [comment]
Works for me :+1: 

Component | Value
---|---
OS | Ubuntu 16.04.5 LTS
Python version | Python 3.5.2
Pip version | pip 18.1 
Manga-py version | 1.4.1
URL | `https://manhwahentai.com/manhwa/healing-hands-obgyn/`


~~~ bash
pipenv run manga-py \
    --cbz --zero-fill --rename-pages --no-webp --destination Manga/ -c 1 \
    https://manhwahentai.com/manhwa/healing-hands-obgyn/
~~~

**Comment by paranoid73** [comment]
it's okat , it works now.
