### ISSUE TITLE
Bug: chapters missing in merakiscans.com provider

### ISSUE THREAD

**Issue by gromenauer** [yuru-yuri/manga-dl#144]
# Bug report
Environment :

Description | Data
---|---
OS | Ubuntu 16.04.5 LTS
Python version | Python 3.5.2
Pip version | pip 18.1 
Manga-py version | 1.4.1
URL | `https://merakiscans.com/details/the-dungeon-master`

#### To Reproduce:
~~~ bash
pipenv run manga-py --cbz --zero-fill --rename-pages --no-webp --destination Manga/ https://merakiscans.com/details/the-dungeon-master
~~~

#### Additional context
No downloads, nothing happens

**Comment by 1271** [comment]
The site has changed the engine. Thank. Fixed in next version.

**Comment by 1271** [comment]
Check `>=1.4.2`

**Comment by gromenauer** [comment]
Works OK :+1: 

Component | Value
---|---
OS | Ubuntu 16.04.5 LTS
Python version | Python 3.5.2
Pip version | pip 18.1 
Manga-py version | 1.5.1
URL | `https://merakiscans.com/details/the-dungeon-master`
