### ISSUE TITLE
Request to add a site: lhtranslation

### ISSUE THREAD

**Issue by gromenauer** [yuru-yuri/manga-dl#147]
# Request to add a site

Name | URL
---|---
lhtranslation | `https://read.lhtranslation.com/manga-murabito-desu-ga-nani-ka.html`

**Comment by 1271** [comment]
Hey. Something I completely became lazy. Need to control yourself! )

**Comment by gromenauer** [comment]
OK. You could rest, everything works for me, I will control my manga needs ;)
Just thought that lhtranslation is a good source.

Tried the new site and works OK :+1: 

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 18.1 
Manga-py version | 1.5.2.2
URL | `https://read.lhtranslation.com/manga-murabito-desu-ga-nani-ka.html`

~~~ bash
pipenv run manga-py --cbz --zero-fill --rename-pages --no-webp --destination Manga/ https://read.lhtranslation.com/manga-murabito-desu-ga-nani-ka.html
~~~

**Comment by 1271** [comment]
On the contrary. I want to force myself to work more. :)

**Comment by gromenauer** [comment]
Oh, I was lost in translation then.
