### ISSUE TITLE
manga-py does not download chapters past the first page in Mangadex

### ISSUE THREAD

**Issue by onaka-itai** [yuru-yuri/manga-dl#148]
# Bug report
Description | Data
---|---
OS | Ubuntu 18.04 \ Windows 10
Python version | 3.6.5
Pip version | 9.0.1
Manga-py version | 1.3.29.1
URL | https://mangadex.org/

#### To Reproduce:
1. Find a manga that has a lot of chapters, specifically one that has multiple pages: (e.g. https://mangadex.org/title/21437/atsumare-fushigi-kenkyu-bu/ -- has two pages, with the first page starting at chapter 20 at the time of writing)
2. Use manga-py (manga-py https://mangadex.org/title/21437/atsumare-fushigi-kenkyu-bu/)
3. manga-py only downloads from chapters 20 and above, and none below.

#### Additional context
I also tried doing the following:

manga-py https://mangadex.org/title/21437/atsumare-fushigi-kenkyu-bu/chapters/2/ and though manga-py recognizes it (it asks which language to download), it actually does not download anything.

**Comment by gromenauer** [comment]
Tried to debug it

In https://github.com/yuru-yuri/manga-dl/blob/93f305ad4e1658397c4cc650f0092973b116497e/manga_py/providers/mangadex_com.py#L68
~~~ py
'{}/chapters/{}/)'.format(self._home_url, i) == 'https://mangadex.org/title/21437/a/chapters/2/)'
~~~
but items retrieved corresponds to page 1. 
No clue here.

**Comment by 1271** [comment]
Oh. Excuse me. This is my typo.
There was an extra character in the address ")"

**Comment by gromenauer** [comment]
Works OK for me :+1: 

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 18.1 
Npm version | 3.5.2
Manga-py version | 1.5.2.4
URL | `https://mangadex.org/title/21437/atsumare-fushigi-kenkyu-bu/`

**Comment by 1271** [comment]
I close this issue
If you have questions, feel free to open it again or create a new issue.
Thank!
