### ISSUE TITLE
Redirection tumangaonline

### ISSUE THREAD

**Issue by gromenauer** [yuru-yuri/manga-dl#151]
This webs have been redirected:

Redirected | Real
--- | ---
`http://tumangaonline.com/` | `https://tmofans.com/`
`http://tumangaonline.me/` | `https://tmofans.com/`

Example url: `https://tmofans.com/library/manga/14274/Kumo-Desu-ga-Nani-ka`

**Comment by 1271** [comment]
Please wait some more.
Now my life is quite intense, but I will soon return to normal :-)

**Comment by 1271** [comment]
This site, like some with cloudflare protection, will now be broken.
I will correct this provider as soon as possible
see https://github.com/Anorov/cloudflare-scrape/issues/188

**Comment by 1271** [comment]
Oh. Still worse.
The site is not just changed the domain.
Bought them:

https://tmofans.com/library/manhua/43261/gold-time-that-you-owe-me
https://otakuteca.com/b/43261/gold-time-that-you-owe-me

**Comment by 1271** [comment]
Sorry, I'm afraid I will refuse to support this site.
At the moment, as I see it, they do not provide online reading options.
