### ISSUE TITLE
Old webs

### ISSUE THREAD

**Issue by gromenauer** [yuru-yuri/manga-dl#152]
Broken links?:

* http://digitalteam1.altervista.org/
* http://heymanga.me/
* http://lector.dangolinenofansub.com/
* http://lector.ytnofan.com/
* http://leomanga.com/
* http://www.mang.as/
* http://santosfansub.com

**Comment by 1271** [comment]
Unfortunately, sometimes sites stop working.
I will list these resources as not working, thanks.
