### ISSUE TITLE
Bug ninemanga

### ISSUE THREAD

**Issue by gromenauer** [yuru-yuri/manga-dl#153]
# Bug report
Environment:

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 18.1 
Npm version | 3.5.2
Manga-py version | 1.5.2.4
URL | `http://es.ninemanga.com/manga/Kumo%20Desu%20ga-%20Nani%20ka%3F.html`

#### To Reproduce:

~~~ bash
pipenv run manga-py --cbz --zero-fill --rename-pages --no-webp --destination Manga/ http://es.ninemanga.com/manga/Kumo%20Desu%20ga-%20Nani%20ka%3F.html -c 1
~~~

#### Additional context
Only one image downloaded multiple times, but not corresponding to the comic.

**Comment by 1271** [comment]
Please wait some more.
Now my life is quite intense, but I will soon return to normal :-)

**Comment by 1271** [comment]
Please, check `manga-py 1.5.3`

**Comment by gromenauer** [comment]
Works OK in `1.5.3` :+1: 

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 18.1 
Npm version | 3.5.2
Manga-py version | 1.5.3
URL | `http://es.ninemanga.com/manga/Kumo%20Desu%20ga-%20Nani%20ka%3F.html`
