### ISSUE TITLE
No download for fanfox.net

### ISSUE THREAD

**Issue by momsen** [yuru-yuri/manga-dl#156]
# Bug report
Environment (please complete the following information):

Description | Data
---|---
OS | Archlinux
Python version | 3.7.2
Pip version | 18.1
Manga-py version | 1.5.2.4
URL | http://fanfox.net/manga/we_broke_up/

#### To Reproduce:
`manga-py http://fanfox.net/manga/we_broke_up/`

#### Additional context
I get multiple JSONDecodeErrors:
`[JSONDecodeError('Extra data: line 1 column 2831 (char 2830)')]...`
(I suppose for each chapter)

**Comment by 1271** [comment]
Please wait some more.
Now my life is quite intense, but I will soon return to normal :-)

**Comment by 1271** [comment]
Please, check `manga-py 1.5.3`

**Comment by gromenauer** [comment]
Works OK for me :+1: 

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 18.1 
Npm version | 3.5.2
Manga-py version | 1.5.3
URL | `http://fanfox.net/manga/we_broke_up/`

**Comment by momsen** [comment]
Works for me as well. Thank you very much for fixing this!
