### ISSUE TITLE
lhtranslation.net internal jpg without extension

### ISSUE THREAD

**Issue by gromenauer** [yuru-yuri/manga-dl#158]
# Bug report

Provider `lhtranslation.net` seems to work OK, but in this strange case one `cbr` have all internal files without the `.jpg` suffix.

Environment :

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.0.3 
Npm version | 3.5.2
Manga-py version | 1.5.3.1
URL | `https://lhtranslation.net/manga-battle-mexia.html`

#### To Reproduce:

1. ~~~ bash
   pipenv run manga-py --cbz --zero-fill --rename-pages --no-webp \
      --destination Manga/ -c 1 \
      https://lhtranslation.net/manga-battle-mexia.html
   ~~~
2. Unzip `vol_001-0.cbz`

#### Additional context
 `vol_001-0.cbz` contains:
* `info.txt`
* `000`
* `001`
* `002`
* ...
* `063`
* `064`

but no `.jpg` extension

**Comment by 1271** [comment]
This will be fixed in the next update.
thank

**Comment by gromenauer** [comment]
Works OK :+1: 

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.0.3 
Npm version | 3.5.2
Manga-py version | 1.5.4
URL | `https://lhtranslation.net/manga-battle-mexia.html -c 1`
