### ISSUE TITLE
problem retrieving lhtranslation.net files hosted in Imgur

### ISSUE THREAD

**Issue by gromenauer** [yuru-yuri/manga-dl#159]
# Bug report
Environment:

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.0.3 
Npm version | 3.5.2
Manga-py version | 1.5.3.1
URL | `https://lhtranslation.net/manga-dolkara.html`

#### To Reproduce:
~~~ bash
pipenv run manga-py --cbz --zero-fill --rename-pages --no-webp --destination Manga/ https://lhtranslation.net/manga-dolkara.html
~~~

#### Additional context
In chapter 14 and 15, images are hosted in `Imgur` and `jpg` files contains `html` instead of the image.

**Comment by 1271** [comment]
This will be fixed in the next update.
thank

**Comment by gromenauer** [comment]
Works OK :+1: 

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.0.3 
Npm version | 3.5.2
Manga-py version | 1.5.4
URL | `https://lhtranslation.net/manga-dolkara.html`
