### ISSUE TITLE
Feature request: rename files with errors

### ISSUE THREAD

**Issue by gromenauer** [yuru-yuri/manga-dl#161]
# Feature request
**Is your feature request related to a problem? Please describe.**
Yes.
When a download partially fails and `manga-dl` generate a page error:
* With error `Warning: 0 bit image downloaded, please check for redirection or broken content`
* If `manga-dl` detects strange content (In the future, if #160 gets approved and implemented)

A file is generated that seems valid.

**Describe the solution you'd like**
Generate a file marked as error: Example: `vol_001-0.ERROR.cbz`

**Comment by gromenauer** [comment]
Seems OK. But I have no errors to test it :satisfied:
Feel free to close it. 
I will post something here If I get an `Warning: 0 bit image downloaded, please check for redirection or broken content` to test it.

**Comment by 1271** [comment]
Let it be open until you check :-)
I'm sorry I had to wait so long for all this.
I finally dismantled part of what prevented work :-)

**Comment by 1271** [comment]
Let it be open until you check :-)
I'm sorry I had to wait so long for all this.

**Comment by gromenauer** [comment]
Work almost OK

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.1.1 
Npm version | 3.5.2
Manga-py version | 1.6.0
URL | `http://heavenmanga.vip/denma/`

Example:
~~~ bash
pipenv run manga-py --cbz --zero-fill --rename-pages --no-webp \
  --show-current-chapter-info --destination Manga/ \
  http://heavenmanga.vip/denma/ \
  -c 2 -s 230
~~~

Output file:
~~~
vol_229-0..ERRORcbz
~~~

Seems that https://github.com/yuru-yuri/manga-dl/blob/ca4b23f594746ba059de222a8fc3b5f158ace7c8/manga_py/provider.py#L175 should be:
~~~ py
 additional_data_name = 'ERROR.'
~~~

**Comment by 1271** [comment]
Oops ))) Thx

**Comment by gromenauer** [comment]
Works OK :+1: 

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.1.1 
Npm version | 3.5.2
Manga-py version | 1.7.0
URL | `http://heavenmanga.vip/denma/`
