### ISSUE TITLE
Bug webtoons. Only 10 pages are scanned.

### ISSUE THREAD

**Issue by gromenauer** [yuru-yuri/manga-dl#163]
# Bug report
Environment (please complete the following information):

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.0.3 
Npm version | 3.5.2
Manga-py version | 1.5.3.2
URL | `https://www.webtoons.com/en/fantasy/the-gamer/list?title_no=88`

#### To Reproduce:
~~~ bash
pipenv run manga-py --cbz --zero-fill --rename-pages --no-webp --destination Manga/ 'https://www.webtoons.com/en/fantasy/the-gamer/list?title_no=88'
~~~

#### Additional context

It only downloads from `vol_000-season-3-ep-35.cbz` to the latest chapter.

It's an edge case, only the 10 first pages are scanned for chapters:
* `https://www.webtoons.com/en/fantasy/the-gamer/list?title_no=88&page=1`
...
* `https://www.webtoons.com/en/fantasy/the-gamer/list?title_no=88&page=10`

The rest are not scanned and it's chapters discarded:
* `https://www.webtoons.com/en/fantasy/the-gamer/list?title_no=88&page=11`
...
* `https://www.webtoons.com/en/fantasy/the-gamer/list?title_no=88&page=27`

**Comment by 1271** [comment]
Ohhh....
It was a long time :-)

![image](https://user-images.githubusercontent.com/1452243/56211021-b10ba200-605f-11e9-92f8-df78c91478f8.png)

**Comment by gromenauer** [comment]
Works OK :+1: 

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.0.3 
Npm version | 3.5.2
Manga-py version | 1.5.4
URL | `https://www.webtoons.com/en/fantasy/the-gamer/list?title_no=88`



~~~ bash
pipenv run manga-py --cbz --zero-fill --rename-pages --no-webp \
    --destination Manga/ 'https://www.webtoons.com/en/fantasy/the-gamer/list?title_no=88' \
    --print-json --simulate \
| grep '"path": "'
~~~

~~~
      "path": "~/Manga/the-gamer/vol_000-ep-1.cbz",
      "path": "~/Manga/the-gamer/vol_001-ep-2.cbz",
...
      "path": "~/Manga/the-gamer/vol_268-season-4-ep-74.cbz",
      "path": "~/Manga/the-gamer/vol_269-season-4-ep-75.cbz",
~~~
