### ISSUE TITLE
Request to add mangaheaven.us

### ISSUE THREAD

**Issue by gromenauer** [yuru-yuri/manga-dl#164]
# Request to add a site

Description | Data
---|---
mangaheaven.us | `http://mangaheaven.us/manga/virtual-world-close-combat-mage`

Seems similar to `mangakakalot` site

**Comment by 1271** [comment]
I think to do it for version 2.0
Thank.

**Comment by gromenauer** [comment]
What's the status on 2.0?
Needs beta testing?

**Comment by 1271** [comment]
Oh. Never mind. Yesterday I was not myself. )

**Comment by 1271** [comment]
Please check for updates :-)

**Comment by 1271** [comment]
I'm having trouble accessing the site.
Unfortunately, it doesn’t open at me even through VPN

**Comment by gromenauer** [comment]
`http://mangaheaven.us` is a parked domain now.

Maybe it migrated to:
* `http://mangaheaven.xyz/` &rarr; `http://mangaheaven.xyz/manga/virtual-world-close-combat-mage`
* `https://mangaheaven.club/` &rarr; `https://mangaheaven.club/read-manga/virtual-world-close-combat-mage`

**Comment by 1271** [comment]
Hi. May I ask you to check all your open issue? This is a bit confusing :)
Thanks!

**Comment by gromenauer** [comment]
Oops! :sweat_smile:
Used only notifications to follow the repo. I will take a look.

**Comment by gromenauer** [comment]
Works OK in 1.7.2 :+1:

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.1.1 
Npm version | 3.5.2
Manga-py version | 1.7.2
URL | `https://mangaheaven.club/read-manga/virtual-world-close-combat-mage`
URL | `http://mangaheaven.xyz/manga/hero-i-quit-a-long-time-ago`

**Comment by 1271** [comment]
Thank you for what you do :-)

**Comment by gromenauer** [comment]
My pleasure. Thank you too for your hard work.
