### ISSUE TITLE
Request to add a site mangasushi

### ISSUE THREAD

**Issue by gromenauer** [yuru-yuri/manga-dl#166]
# Request to add a site

Description | Data
---|---
Url to add | `https://mangasushi.net/manga/yuukyuu-no-gusha-asley-no-kenja-no-susume/`

**Comment by 1271** [comment]
Please check for updates :-)

**Comment by gromenauer** [comment]
:bug: Tried, but gives errors.

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.1.1 
Npm version | 3.5.2
Manga-py version | 1.5.6.1
URL | `https://mangasushi.net/manga/yuukyuu-no-gusha-asley-no-kenja-no-susume/`

~~~ bash
pipenv run manga-py --cbz --zero-fill --rename-pages --no-webp --destination Manga/ https://mangasushi.net/manga/yuukyuu-no-gusha-asley-no-kenja-no-susume/
~~~

Output:
~~~
Error processing file: vol_002-0
Error processing file: vol_003-0
Error processing file: vol_004-0
Error processing file: vol_005-0
Error processing file: vol_006-0
Error processing file: vol_007-0
Error processing file: vol_008-0
Error processing file: vol_009-0
Error processing file: vol_010-0
Error processing file: vol_011-0
Error processing file: vol_012-0
Error processing file: vol_013-0
Error processing file: vol_014-0
~~~

**Comment by 1271** [comment]
Oh ... I'll check it out. Thank

**Comment by gromenauer** [comment]
The bug persists in 1.8.0 :bug: 

Tried with manga-py-docker:

Component | Value
---|---
OS | Debian GNU/Linux 8 (jessie)
Python version | Python 3.6.8
Pip version | pip 19.1.1 
Npm version | 6.9.0
Manga-py version | 1.8.0
URL | `https://mangasushi.net/manga/yuukyuu-no-gusha-asley-no-kenja-no-susume/`

~~~ bash
docker run -it mangadl/manga-py
manga-user@074f07530072:/home/manga$ manga-py https://mangasushi.net/manga/yuukyuu-no-gusha-asley-no-kenja-no-susume/
~~~
Output:
~~~
Error processing file: vol_002
Error processing file: vol_003
Error processing file: vol_004
Error processing file: vol_005
Error processing file: vol_006
Error processing file: vol_007
Error processing file: vol_008
Error processing file: vol_009
Error processing file: vol_010
Error processing file: vol_011
Error processing file: vol_012
Error processing file: vol_013
Error processing file: vol_014
Error processing file: vol_015
Error processing file: vol_016
Error processing file: vol_017
Error processing file: vol_018
Error processing file: vol_019
Error processing file: vol_020
~~~

**Comment by 1271** [comment]
I incorrectly changed url
Now it should work)

**Comment by gromenauer** [comment]
Works in 1.8.1 :+1: 

Component | Value
---|---
OS | Debian GNU/Linux 8 (jessie)
Python version | Python 3.6.8
Pip version | pip 19.1.1 
Manga-py version | 1.8.1
URL | `https://mangasushi.net/manga/yuukyuu-no-gusha-asley-no-kenja-no-susume/`
