### ISSUE TITLE
replace japscan.cc and japscan.com with japscan.to

### ISSUE THREAD

**Issue by two43** [yuru-yuri/manga-dl#170]
Both domains redirect to japscan.to

**Comment by 1271** [comment]
Thank. Will be fixed in the next release.

**Comment by 1271** [comment]
I replaced the domain, but this does not solve the main problem
Unfortunately, some may experience difficulties with this site, because it is currently protected by cloudflare (at the moment the tool that solves the problem of entering the site is broken)

**Comment by gromenauer** [comment]
Tried, but nothing happens :bug: (no worried, I don't understand french):

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.1.1 
Npm version | 3.5.2
Manga-py version | 1.5.5.1
URL | `https://www.japscan.to/manga/world-trigger/`
URL | `https://www.japscan.to/manga/bocchan-to-maid/`

**Comment by 1271** [comment]
hmm ... I'll check it one more time anyway. thank
