### ISSUE TITLE
Request to add mangafans.us

### ISSUE THREAD

**Issue by gromenauer** [yuru-yuri/manga-dl#172]
# Request to add a site

Description | Site | Example
---|---|---
Url to add | `https://mangafans.us/` | `https://mangafans.us/manga/npc`

**Comment by gromenauer** [comment]
This (not implemented) seems to be the same:
`https://mangahot.org/read-manga/npc`

This (already implemented) seems only similar:
`https://mangakakalot.com/manga/npc`

**Comment by 1271** [comment]
Please check for updates :-)

**Comment by gromenauer** [comment]
Maybe other one, this still pending :smiley: 

URL | Result
---|---
`https://mangafans.us/manga/npc` | Provider not found
`https://mangahot.org/read-manga/npc` | Provider not found

**Comment by 1271** [comment]
Oops... :baby_chick:

**Comment by gromenauer** [comment]
Works OK in 1.7.2 :+1: 

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.1.1 
Npm version | 3.5.2
Manga-py version | 1.7.2
URL | `https://mangafans.us/manga/npc`
