### ISSUE TITLE
Request to add mangadex.info

### ISSUE THREAD

**Issue by gromenauer** [yuru-yuri/manga-dl#175]
# Request to add a site

Description | Data
---|---
Url to add | `https://mangadex.info/`

**Comment by 1271** [comment]
Oh. They changed the domain.
Thank. Will be fixed soon!

**Comment by gromenauer** [comment]
Not the same as `https://mangadex.org/` just "borrowing" the name.

**Comment by 1271** [comment]
Please check for updates :-)

**Comment by gromenauer** [comment]
Seems to download OK, but it download 0 bytes images without complaining 

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.1.1 
Npm version | 3.5.2
Manga-py version | 1.5.6.1
URL | `https://mangadex.info/manga/sword-art-online-project-alicization`

~~~ bash
pipenv run manga-py --cbz --zero-fill --rename-pages --no-webp --destination /home/alicia/Descargas/Pendiente/Manga/ https://mangadex.info/manga/sword-art-online-project-alicization
~~~ 
In this comic, files from `vol_001-0.cbz` to `vol_007-0.cbz` contains only 0 bytes images

**Comment by gromenauer** [comment]
Tried a second example, this is OK :+1: 

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.1.1 
Npm version | 3.5.2
Manga-py version | 1.5.6.1
URL | `https://mangadex.info/manga/kage-no-jitsuryokusha-ni-naritakute`

**Comment by 1271** [comment]
I will check it out. Thanks you

**Comment by 1271** [comment]
I will close it. If you still have problems, open this issue again.
thank

**Comment by gromenauer** [comment]
Still 0 bytes for me.

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.1.1 
Npm version | 3.5.2
Manga-py version | 1.7.0
URL | `https://mangadex.info/manga/sword-art-online-project-alicization`

Example `vol_001-0.cbz`:
~~~ bash
pipenv run manga-py --cbz --zero-fill --rename-pages --no-webp \
  --show-current-chapter-info --destination Manga/ \
  https://mangadex.info/manga/sword-art-online-project-alicization \
  -c 2 -s 1
~~~

**Comment by 1271** [comment]
Thanks for noticing the missing button.
Now I know )

**Comment by gromenauer** [comment]
Works for me :+1: 

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.1.1 
Npm version | 3.5.2
Manga-py version | 1.7.2
URL | `https://mangadex.info/manga/sword-art-online-project-alicization`
