### ISSUE TITLE
Bug: Can't download from kissmanga

### ISSUE THREAD

**Issue by juh9870** [yuru-yuri/manga-dl#179]
# Bug report
Environment (please complete the following information):

Description | Data
---|---
OS | Windows 7
Python version | 3.5.2
Pip version | 18.1
Manga-py version | 1.5.4
Node.js version | 10.15.3
cfscrape version | 1.9.7
URL | Any manga hosted on kissmanga

#### Additional context
When i'm trying to download from kissmanga it shows this insane errorlog
![image](https://user-images.githubusercontent.com/15922601/57180725-3088d600-6e94-11e9-9243-5c4c7a618f3d.png)

**Comment by gromenauer** [comment]
Seems the same as https://github.com/yuru-yuri/manga-dl/issues/171#issuecomment-484475789

@1271 replied then:
> Unfortunately, this is currently broken for all sites protected by cloudflare (see https://github.com/Anorov/cloudflare-scrape/issues)

Maybe `cloudflare-scrape` is stagnated https://github.com/Anorov/cloudflare-scrape/issues/231 (?!?)

**Comment by 1271** [comment]
Oh! I have not seen this issue.
Thank you for your attention.
As soon as I return to the project (in 3 days), I will apply these changes.
Thank )

**Comment by 1271** [comment]
Hi. Did you check it? Are there any difficulties? Can I close this?

**Comment by juh9870** [comment]
Oh, yes, sorry, forgot to check it, it works fine now

**Comment by gromenauer** [comment]
Works for me too :+1: (with a little help  #182)  :

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.1.1 
Npm version | 3.5.2
Manga-py version | 1.5.5.1
URL | `https://kissmanga.com/Manga/Sewayaki-Kitsune-no-Senko-san`
