### ISSUE TITLE
Segfault during installation

### ISSUE THREAD

**Issue by onaka-itai** [yuru-yuri/manga-dl#187]
# Bug report
Environment:

Description | Data
---|---
OS | Ubuntu 18.04
Python version | 3.6.5
Pip version | 9.0.1
Manga-py version | 1.3.29.1

#### To Reproduce:
1. Install with pip3 and enable verbosity `pip3 install manga-py -v`
1. See log. Seems to be due to some py2 code in js2py:

```
  *** Error compiling '/tmp/pip-build-ocbi3pn6/js2py/js2py/internals/speed.py'...
    File "/tmp/pip-build-ocbi3pn6/js2py/js2py/internals/speed.py", line 50
      print timeit(
                 ^
  SyntaxError: invalid syntax
  
  *** Error compiling '/tmp/pip-build-ocbi3pn6/js2py/js2py/test_internals.py'...
    File "/tmp/pip-build-ocbi3pn6/js2py/js2py/test_internals.py", line 9
      print seval.eval_js_vm(x)
                ^
  SyntaxError: invalid syntax
  



Successfully installed asn1crypto-0.24.0 brotli-1.0.7 certifi-2019.6.16 cffi-1.12.3 chardet-3.0.4 cloudscraper-1.1.18 cryptography-2.7 idna-2.8 js2py-0.66 pycparser-2.19 pyjsparser-2.7.1 pyopenssl-19.0.0 pytz-2019.1 requests-2.22.0 requests-toolbelt-0.9.1 six-1.12.0 tzlocal-1.5.1 urllib3-1.25.3
Cleaning up...
Segmentation fault (core dumped)
```
Is there a way to bypass this?

**Comment by 1271** [comment]
try it:
```bash
python3 -mpip uninstall js2py manga-py
python3 -mpip install js2py loguru
python3 -mpip install manga-py
```
loguru causes installation error (I will check it)

My js2py installation also ended with an error for python 3.7
As I understand it, at the moment this situation is for everyone (https://github.com/PiotrDabkowski/Js2Py/issues/159)

**Comment by 1271** [comment]
Hey. Are you still having difficulty installing?

**Comment by onaka-itai** [comment]
Hi, I tried uninstalling and reinstalling as you've outlined above, but it still returns a segfault. I still am not able to use manga-py.

**Comment by 1271** [comment]
Tell me. What version of nodejs do you have?
Actually, I have no ideas.
Each release is tested on a clean system and, as you can see, this should work well.
Example: https://travis-ci.org/yuru-yuri/manga-dl/jobs/549029510#L1543

Install requirements here line:
https://github.com/yuru-yuri/manga-dl/blob/stable_1.x/.travis.yml#L15

As I understand it, the line `python3 -mpip install js2py` causes an error?


Tried it?
https://hub.docker.com/r/mangadl/manga-py

**Comment by 1271** [comment]
Hi. Are you still having problems?

**Comment by onaka-itai** [comment]
Hello, sorry for the late response, but I am still having problems installing. At this point I'm not sure what's causing it.

My nodejs version is v8.10.0

Running python3 -mpip install js2py does not cause an error:

```
Collecting js2py
Collecting pyjsparser>=2.5.1 (from js2py)
Collecting tzlocal>=1.2 (from js2py)
Collecting six>=1.10 (from js2py)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting pytz (from tzlocal>=1.2->js2py)
  Using cached https://files.pythonhosted.org/packages/3d/73/fe30c2daaaa0713420d0382b16fbb761409f532c56bdcc514bf7b6262bb6/pytz-2019.1-py2.py3-none-any.whl
Installing collected packages: pyjsparser, pytz, tzlocal, six, js2py
Successfully installed js2py-0.66 pyjsparser-2.7.1 pytz-2019.1 six-1.12.0 tzlocal-1.5.1
```
However, when I run `python3 -mpip install js2py`, I get the same error as before:
```

  *** Error compiling '/tmp/pip-build-y3dqyek6/js2py/js2py/internals/speed.py'...
    File "/tmp/pip-build-y3dqyek6/js2py/js2py/internals/speed.py", line 50
      print timeit(
                 ^
  SyntaxError: invalid syntax
  
  *** Error compiling '/tmp/pip-build-y3dqyek6/js2py/js2py/test_internals.py'...
    File "/tmp/pip-build-y3dqyek6/js2py/js2py/test_internals.py", line 9
      print seval.eval_js_vm(x)
                ^
  SyntaxError: invalid syntax
  
  changing mode of /home/onakaitai/.local/bin/manga-py to 775
Successfully installed Pillow-6.0.0 asn1crypto-0.24.0 brotli-1.0.7 certifi-2019.6.16 cffi-1.12.3 chardet-3.0.4 cloudscraper-1.1.24 cryptography-2.7 cssselect-1.0.3 html-purifier-0.1.9 idna-2.8 js2py-0.66 loguru-0.3.0 lxml-4.3.4 manga-py-1.7.1 packaging-19.0 progressbar2-3.42.0 pycparser-2.19 pycrypto-2.6.1 pyexecjs-1.5.1 pyjsparser-2.7.1 pyopenssl-19.0.0 pyparsing-2.4.0 python-utils-2.3.0 pytz-2019.1 requests-2.22.0 requests-toolbelt-0.9.1 selenium-3.141.0 six-1.12.0 tzlocal-1.5.1 urllib3-1.25.3
Cleaning up...
Segmentation fault (core dumped)
```

**Comment by onaka-itai** [comment]
Update:

Got it installed but not cleanly. The segfault still happens, though.
```

  changing mode of /home/onakaitai/.local/bin/manga-py to 775
Successfully installed Pillow-6.0.0 asn1crypto-0.24.0 brotli-1.0.7 certifi-2019.6.16 cffi-1.12.3 chardet-3.0.4 cloudscraper-1.1.24 cryptography-2.7 cssselect-1.0.3 html-purifier-0.1.9 idna-2.8 js2py-0.66 loguru-0.3.0 lxml-4.3.4 manga-py-1.7.1 packaging-19.0 progressbar2-3.42.0 pycparser-2.19 pycrypto-2.6.1 pyexecjs-1.5.1 pyjsparser-2.7.1 pyopenssl-19.0.0 pyparsing-2.4.0 python-utils-2.3.0 pytz-2019.1 requests-2.22.0 requests-toolbelt-0.9.1 selenium-3.141.0 six-1.12.0 tzlocal-1.5.1 urllib3-1.25.3
Cleaning up...
Segmentation fault (core dumped)
```

**Comment by 1271** [comment]
> However, when I run python3 -mpip install js2py, I get the same error as before:

Did you mean install manga-py?

Have you tried installing the docker version of manga-py?


P.S.

Have you tried to download the archive with manga-py and use it without installation?

**Comment by onaka-itai** [comment]
Yes, that's correct. I meant manga-py, apologies.

Docker version works. Also, I did a check out of the latest revision set it up that way and it also works. I got the version from pip working but it segfaulted during installation, but ended up working anyway. Very odd behaviour!

**Comment by 1271** [comment]
Can I consider the problem solved?

**Comment by onaka-itai** [comment]
Yes, closed!
