### ISSUE TITLE
Specific manga/manhwa won't download. (manhwahentai.com)

### ISSUE THREAD

**Issue by nothuman00** [yuru-yuri/manga-dl#188]
# Bug report
Environment (please complete the following information):

Description | Data
---|---
OS | Windows 10
Python version | 3.6.5
Pip version | 9.0.1
Manga-py version | 1.5.4
URL | https://manhwahentai.com/manhwa/hidden-feeling/

#### To Reproduce:
cmd : manga-py https://manhwahentai.com/manhwa/hidden-feeling/ -d /manhwa/hentai/HiddenFeeling --cbz --rename-pages

#### Additional context

(base) C:\Users\anon>manga-py https://manhwahentai.com/manhwa/hidden-feeling/ -d /manhwa/HiddenFeeling --cbz --rename-pages --no-webp
  File "c:\users\anon\anaconda3\lib\site-packages\manga_py\provider.py", line 81, in process
    self.loop_chapters()
  File "c:\users\anon\anaconda3\lib\site-packages\manga_py\provider.py", line 112, in loop_chapters
    self._info.add_volume(self.chapter_for_json(), self.get_archive_path())
  File "c:\users\anon\anaconda3\lib\site-packages\manga_py\provider.py", line 159, in get_archive_path
    _path = remove_file_query_params(self.get_archive_name())
  File "c:\users\anon\anaconda3\lib\site-packages\manga_py\providers\helpers\std.py", line 8, in get_archive_name
    idx = self.get_chapter_index()
  File "c:\users\anon\anaconda3\lib\site-packages\manga_py\providers\manhwahentai_com.py", line 8, in get_chapter_index
    return self.re.search(r'/chapter-(\d+(?:-\d+)?)', self.chapter).group(1)

**Comment by 1271** [comment]
Thanks for the issue. In the process )

**Comment by 1271** [comment]
Please, check new version

**Comment by redenvalerio** [comment]
Hi! 
I tried the new version and it works now somehow. but there still remaining bug which I don't know if its in the tool or the site itself.

I'll attach the whole progress.
much thanks !

[bug.txt](https://github.com/yuru-yuri/manga-dl/files/3307873/bug.txt)

**Comment by 1271** [comment]
Oh. This is not a mistake in your case.
See here https://github.com/yuru-yuri/manga-dl/blob/ca4b23f594746ba059de222a8fc3b5f158ace7c8/manga_py/http/__init__.py#L93-L99
And here https://github.com/yuru-yuri/manga-dl/blob/ca4b23f594746ba059de222a8fc3b5f158ace7c8/manga_py/http/__init__.py#L70-L75


The fact is that at the specified url there are very small images (the size is checked less than 128 bytes)
At the moment, you can safely ignore it.
I think it won't hurt the absence of those images (as you could see, there’s just a black line a few pixels high)

**Comment by 1271** [comment]
I have slightly reduced the limit for the error (zero-file)
Now you should not receive a message about it.

I close this issue. If you still have questions, open this issue again or create a new one.
thank

**Comment by 1271** [comment]
I will close it. If you have any questions, click "Reopen issue"
