### ISSUE TITLE
Skip argument error

### ISSUE THREAD

**Issue by 1271** [yuru-yuri/manga-dl#190]
manga-py http://url --reverse-downloading -s 1 -c 2

Download one chapter only
Need fix

**Comment by gromenauer** [comment]
Tried and downloads one.

~~~ bash
pipenv run manga-py --cbz --zero-fill --rename-pages --no-webp --show-current-chapter-info \
  --destination Manga/ https://readcomicsonline.ru/comic/the-flash-2016 \
  --reverse-downloading -s 1 -c 2
~~~

Component | Value
---|---
OS | Ubuntu 16.04.6 LTS
Python version | Python 3.5.2
Pip version | pip 19.1.1 
Npm version | 3.5.2
Manga-py version | 1.8.0
URL | `https://readcomicsonline.ru/comic/the-flash-2016`

**Comment by 1271** [comment]
Hmm .. I'll check your case.
Although it worked for me)

**Comment by gromenauer** [comment]
Seems that version 1.8.0 have a general bug #195, and this is why I tried and only downloads one.

**Comment by gromenauer** [comment]
Works with the fix :+1:
