### ISSUE TITLE
Cannot download manga from lhscan,net

### ISSUE THREAD

**Issue by owen800q** [yuru-yuri/manga-dl#191]
# Bug report
Environment (please complete the following information):
The latest docker image
URL | https://lhscan.net/manga-tono-kanri-o-shite-miyou-raw.html

#### Additional context
![image](https://user-images.githubusercontent.com/19252045/59960232-f7fe9380-94f7-11e9-9d0c-430b57961378.png)

**Comment by 1271** [comment]
Thx for issue ^_^

**Comment by 1271** [comment]
Ahaha
Try to open it yourself.

There really are no images


https://lhscan.net/read-tono-kanri-o-shite-miyou-raw-chapter-1.html

**Comment by owen800q** [comment]
Finally solved the problem by installing node.

> https://lhscan.net/read-tono-kanri-o-shite-miyou-raw-chapter-1.html
hahh, I made a stupid mistake....

**Comment by gromenauer** [comment]
It creates correct labeled files (for me) `vol_001-0.ERROR.cbz` `vol_002-0.ERROR.cbz` ...
