### ISSUE TITLE
Feature: Make it comic book reader friendly

### ISSUE THREAD

**Issue by gromenauer** [yuru-yuri/manga-dl#42]
If you use it with a comic book reader like [Mcomicx](https://sourceforge.net/projects/mcomix/) two things will make it easier:
* Having a `*.cbz` extension to associate it to the comic book reader.
* Having the name of the comic in every file to reflect it in the bookmark, and then know where you left that comic six month ago.

My proposals:
* Add a `--cbz` flag to the command line to produce files `*.cbz` extension
* Add a `--name-in-files` flag to the command line to put the name of the comic in every file
(or a --comicbook to do both, whatever you see better).

**Comment by 1271** [comment]
Thanks for the issue.
https://en.wikipedia.org/wiki/Comic_book_archive#Design
* .cbz maybe? its ok?

Rar is not a free archiver. In addition, he will not give more compression.

If * .cbz is good, this is not a problem.

**Comment by 1271** [comment]
http://acbf.wikia.com/wiki/Advanced_Comic_Book_Format_Wiki

**Comment by 1271** [comment]
Yes, I think I will do it.
Also in manga-py there is now a preview of the manga (although this is not possible on all sites). This will also be realized.

**Comment by gromenauer** [comment]
`*.cbz` is good. Python have [zipfile-objects](https://docs.python.org/3/library/zipfile.html#zipfile-objects) in the standard library.

**Comment by 1271** [comment]
Yes it is.
Now the flag will only rename the archive.
But in the release version, I want to add meta-information about the book.

**Comment by gromenauer** [comment]
`--cbz` Works ok.

**Comment by 1271** [comment]
Unfortunately, I did not find information about the standards for * .cbz / * .cbr format
As the wiki writes, it's not at all:
https://wiki.mobileread.com/wiki/CBR_and_CBZ#Metadata

Therefore, everything will remain as it is.

If there are any questions or suggestions, I'm ready to listen.
