### ISSUE TITLE
Unordered chapters when the web numbered them poorly

### ISSUE THREAD

**Issue by gromenauer** [yuru-yuri/manga-dl#44]
I have discovered another use case that could be friendlier when using comickbook readers. But I don't know if it can be improved from `manga-dl` side.

Try (as example):  
~~~ bash
manga-py --cbz https://www.readmng.com/kumo-desu-ga-nani-ka
~~~
It downloads ok, reads ok, but the reading order is not correct and it's the web fault:
~~~
vol_000.cbz
vol_1.2.cbz
vol_1.1.cbz
vol_001.cbz
...
~~~
You could rename it manually:
~~~
vol_000.cbz
vol_001.0.cbz
vol_001.1.cbz
vol_001.2.cbz
...
~~~
But if you want to download the latest chapter, then the renamed chapters will be downloaded again :/

Possible solutions:
* Add a chapter field in every `info.txt` field and check it when downloading.
  * Pro: You can rename the chapters as you like
  * Con: Adds a step when downloading, makes the process slower, if you misname a chapter it will never be downloaded again (except if you ade a `--verbose` option to see what is found previously)
* Add a external file where the renames are stored:
  * Pro: You can rename the chapters as you like, is faster than the above solution.
  * Con: More complicated for the user.
* Prefix the name with the web order appearance number.
  * Pro: It should be ordered as the web presents it.
  * Con: If the order is reversed or the web is mistaken you have no way to correct it. It impedes to get the same manga from different webs.
* Thinking of something else. I'm not convinced of the above solutions, they are there to brainstorm.

**Comment by 1271** [comment]
Thanks for issue.

The reason for this numbering of chapters is that it displays (in most cases) the real number of the chapter.
Ie, if not all are accessible for reading, the program tries to observe the actual numbering.
For example, if Chapter 3 is not available, archives with numbers 1, 2, 4, 5, etc will be downloaded.

Concerning the file info.txt:
Do you offer to store it in a folder with archives?
I do not quite understand how this can help the reader.

Solution 3 is real. Information about chapters can be stored, for example, in a file (the above-mentioned info.txt, for example).
Then you can not worry about the problems with the Internet.

The sorting option can also be something like this:

000-vol_ {real-chapter-num} .cbz
001-vol_ {real-chapter-num} .cbz
002-vol_ {real-chapter-num} .cbz
003-vol_ {real-chapter-num} .cbz
etc

This will give normal sorting.

---

I would be very happy if the various websites comply with the standard naming convention. But this, unfortunately, is not so. :sweat:

**Comment by 1271** [comment]
Oh. That's my fault!
I fixed it.
In the next update, everything will be fine.
The site changed the addresses of the chapters.
Earlier in the end was /
Now he's gone.
This led to the fact that the chapter number was processed "as is", without formatting

**Comment by gromenauer** [comment]
Sorry for the delay.

Done:
~~~ bash
pipenv shell
pip install manga-py -U
~~~

I got `manga-py==1.1.4`

~~~ bash
manga-py --cbz https://www.readmng.com/kumo-desu-ga-nani-ka
ls Manga/kumo-desu-ga-nani-ka/
~~~

It's better, but it's not alphabetically ordered.
~~~
vol_000.cbz
vol_001-2.cbz
vol_001.cbz
vol_002-1.cbz
vol_003.cbz
vol_004.cbz
vol_005-1.cbz
vol_005-2.cbz
vol_005.cbz
...
~~~

To read it with a comic book reader it should be as:

~~~
vol_000.cbz
vol_001-0.cbz
vol_001-2.cbz
vol_002-1.cbz
vol_003.cbz
vol_004.cbz
vol_005-0.cbz
vol_005-1.cbz
vol_005-2.cbz
...
~~~

or maybe as: 

~~~
vol_000-0.cbz
vol_001-0.cbz
vol_001-2.cbz
vol_002-1.cbz
vol_003-0.cbz
vol_004-0.cbz
vol_005-0.cbz
vol_005-1.cbz
vol_005-2.cbz
...
~~~

**Comment by 1271** [comment]
Ohh. I understood you.
Good. In the next update i will add 0 to nonexistent sections.
`or maybe as:`

**Comment by 1271** [comment]
Please, update this to >=1.2.0.1!
Use parameter `--zero-fill` for this effect:

![image](https://user-images.githubusercontent.com/1452243/41176260-69105168-6b68-11e8-9494-9fc77b7db24a.png)

**Comment by gromenauer** [comment]
Tried, and works ok with `manga-py==1.2.0.1`
~~~ bash
pip install manga-py -U
manga-py --cbz --zero-fill https://www.readmng.com/kumo-desu-ga-nani-ka
~~~

**Comment by gromenauer** [comment]
Just curious. Are you using any comic reader in Android? 
I'm using [bubble](https://github.com/nkanaev/bubble) for now.

**Comment by 1271** [comment]
Yes.
I'm using [Comic screen](https://play.google.com/store/apps/details?id=com.viewer.comicscreen&hl=en_US). Very cool programm. :smile_cat:
