### ISSUE TITLE
Add simulate option

### ISSUE THREAD

**Issue by gromenauer** [yuru-yuri/manga-dl#46]
Add `simulate` option.

In `youtube-dl` the `simulate` option is described:
~~~
-s, --simulate  Do not download the video and do not write anything to disk
~~~

Use case:
In combination with #40 `--print-json` you could list one comic url possible downloads between days and compare it to know if it still working.

Example:
~~~ bash
manga-py  --print-json --simulate https://www.readmng.com/kumo-desu-ga-nani-ka > kumo-desu-ga-nani-ka.2018-06-08.json
# Ten days before you do the same
manga-py  --print-json --simulate https://www.readmng.com/kumo-desu-ga-nani-ka > kumo-desu-ga-nani-ka.2018-06-18.json
# Compare the results and see if it is the same
diff kumo-desu-ga-nani-ka.2018-06-08.json kumo-desu-ga-nani-ka.2018-06-18.json
~~~

~~~ python
if no_diff_output:
    nothing to do
else:
    new comics or the web structure have changed.
~~~

**Comment by 1271** [comment]
Good.
The output must contain information that the program is going to load and what is already available.
For example, we already have 3 chapters. The output will contain the "skip" flag, for example, with the value "true".

I understand correctly?

---

And another question.

Does it make sense for you to look for images?
This is almost always a long process.

**Comment by 1271** [comment]
Simulation worked now on version >= 1.2.1.1
