### ISSUE TITLE
Installation fails in termux (Android)

### ISSUE THREAD

**Issue by MercuryxLion** [yuru-yuri/manga-dl#48]
To make it work I had to install the following packages:

pkg install clang libclang libclang-dev glib python-dev openssl-dev openssl-tool libcrypt libcrypt-dev libexpat glib-dev libexpat-dev libgc libgc-dev libxslt libxslt-dev pkg-config xmlsec-dev libjpeg-turbo libjpeg-turbo-dev binutils gdbm libandroid-support-dev libbz2 libffi libgcrypt libgpg-error libllvm libsqlite libutil libxml2 libxml2-dev ncurses-ui-libs ndk-stl ndk-sysroot pcre pcre-dev python xmlsec

pip install pillow 

pip install manga-py

**Comment by 1271** [comment]
Hello! I have not tried to install this on android.
Thanks for the instruction! I will definitely add it to README

**Comment by MercuryxLion** [comment]
The principal problem was that some libraries didn't have a version candidate for my architecture, but with those packages I had no problem compiling them. Thank you very much for your work.

**Comment by 1271** [comment]
Thank you for using this!

**Comment by GoluLiliput** [comment]
> To make it work I had to install the following packages:
> 
> pkg install clang libclang libclang-dev glib python-dev openssl-dev openssl-tool libcrypt libcrypt-dev libexpat glib-dev libexpat-dev libgc libgc-dev libxslt libxslt-dev pkg-config xmlsec-dev libjpeg-turbo libjpeg-turbo-dev binutils gdbm libandroid-support-dev libbz2 libffi libgcrypt libgpg-error libllvm libsqlite libutil libxml2 libxml2-dev ncurses-ui-libs ndk-stl ndk-sysroot pcre pcre-dev python xmlsec
> 
> pip install pillow 
> 
> pip install manga-py

Hello... Please cannu share the apk of the repo with me? It would be highly helpful for me 🥺

**Comment by 1271** [comment]
@GoluLiliput https://play.google.com/store/apps/details?id=com.termux

**Comment by gromenauer** [comment]
No playstore and/or FLOSS enthusiast:
Tmux in F-Droid:https://f-droid.org/en/packages/com.termux/
