### ISSUE TITLE
kissmanga.com ERROR: Could not collect tokens

### ISSUE THREAD

**Issue by gromenauer** [yuru-yuri/manga-dl#50]
Got this error:
~~~
manga-py http://kissmanga.com/Manga/Kou-1-Desu-ga-Isekai-de-Joushu-Hajimemashita
ERROR:root:'http://kissmanga.com/Manga/Kou-1-Desu-ga-Isekai-de-Joushu-Hajimemashita' returned an error. Could not collect tokens.
~~~

**Comment by 1271** [comment]
Again, protect the cloudflare. 😞 

Please, update  `cfscrape`
```
 pip install cfscrape -U
```

And update manga-py to >= 1.2.0.4

**Comment by gromenauer** [comment]
~~~
pip install manga-py cfscrape --upgrade
manga-py http://kissmanga.com/Manga/Kou-1-Desu-ga-Isekai-de-Joushu-Hajimemashita

ERROR:root:'http://kissmanga.com/Manga/Kou-1-Desu-ga-Isekai-de-Joushu-Hajimemashita' returned an error. Could not collect tokens.
~~~
Don't know, maybe it's my environment fault or the web broke again.

**Comment by 1271** [comment]
No, no. Run here:

```
pip install cfscrape -U
pip install manga-py -U
```

**Comment by 1271** [comment]
Show output:
```
 pip freeze | grep cfscrape
```

**Comment by gromenauer** [comment]
~~~
cfscrape==1.9.5
manga-py==1.2.0.4
~~~

**Comment by 1271** [comment]
I checked it at work - it works.
(Except for the fact that kilssmanga has complicated the decoding of images, but I will also fix it.)
This can not cause your mistake.

Is the site accessible from the browser? %)

**Comment by 1271** [comment]
I have an idea!
Try to download this release (https://github.com/yuru-yuri/manga-dl/releases/tag/0.2.3.8)

Download the executable file. This is an old branch. She's not in the pip

If this works (in theory, it should cause the same error), then the problem is manga-py.
If it does not work, the problem is somewhere else.

**Comment by 1271** [comment]
Hello, @gromenauer !
From you no news. Did it work?

**Comment by gromenauer** [comment]
Sorry I am stuck in how to sandbox a binary.
Could we skip this kind of test?

**Comment by 1271** [comment]
> Could we skip this kind of test?
Not problem.

There is another question:
Do you have nodejs installed?
This is a mandatory extension for the operation of sites with cloudflare protection.

Please, try this site: http://mangafreak.net (Here, too, the same protection is used)

**Comment by gromenauer** [comment]
~~~ bash
npm --version
3.5.2
~~~
Same error in mangafreak.net:
~~~
ERROR:root:'http://www8.mangafreak.net/Manga/Sozai_Saishuka_No_Isekai_Ryokouki' returned an error. Could not collect tokens.
~~~

Similar error in mangago.me:
~~~
manga-py --cbz --zero-fill --rename-pages --destination ~/Manga/ http://www.mangago.me/read-manga/tensei_ouji_wa_daraketai/
ERROR:root:'http://www.mangago.me/read-manga/tensei_ouji_wa_daraketai/' returned an error. Could not collect tokens.
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/providers/mangago_me.py", line 25, in get_chapters
    content = self.document_fromstring(self.content, '#information', 0)
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/base_classes/static.py", line 24, in document_fromstring
    result = result[idx]
~~~

**Comment by 1271** [comment]
No-no.
Not npm, but node.

Please, check again:

```
import cfscrape
scr = cfscrape.create_scraper()
scr.get_tokens('http://www8.mangafreak.net/Manga/Sozai_Saishuka_No_Isekai_Ryokouki')
```
It's worked?

**Comment by gromenauer** [comment]
~~~
nodejs --version
v4.2.6
~~~
It's really out of date. 
I will look into it, thanks.
