### ISSUE TITLE
flag for rename pages

### ISSUE THREAD

**Issue by gromenauer** [yuru-yuri/manga-dl#52]
Is not `manga-py` fault, but my preferred comic reader have an strange issue ( https://github.com/nkanaev/bubble/issues/68 ) with page names.
My proposal is to add a flag `--rename-pages` to rename the pages in every volume like:
~~~
0001.jpg
0002.jpg
...
~~~
In this way everyone can avoid any page reading weirdness while reading it.
If you don't want to lose the original names it could be stored in the `info.txt` in yaml style like:
~~~ yaml
Site: http://www.funmanga.com/kou-1-desu-ga-isekai-de-joushu-hajimemashita
Downloader: https://github.com/yuru-yuri/manga-dl
Version: 1.2.0.2
Page names:
- 0001.jpg: original_name_of_page_1
- 0002.jpg: original_name_of_page_2
...
~~~

(I can workaround it if it is too much trouble).

**Comment by 1271** [comment]
It's not problem.
Update maga-py and try it.

**Comment by gromenauer** [comment]
Sorry, not working here.

~~~ bash
manga-py --cbz --zero-fill --rename-pages --destination ~/Manga/ http://mangalife.us/manga/For-My-Daughter
~~~
gave this error
~~~
  File "manga_py/base_classes/base.py", line 166, in _image_name
    if idx and len(idx) < 6:  # (.png, .webp) == True, .image-file-jpg == False
TypeError: object of type 'int' has no len()
~~~

Tried changing the line to:
~~~ python
if idx and len(filename) < 6:  # (.png, .webp) == True, .image-file-jpg == False
~~~
but got this warning
~~~
manga_py/base_classes/archive.py:48: UserWarning: Duplicate name: '008.jpg'
  self._archive.write(file[0], file[1])
~~~

**Comment by 1271** [comment]
Thanks for the bug-report. This is my inattention. In 2-3 hours there will be a new release with correction.

> P.S. 
> Good manga. It's a pity no one translated it into my native language yet. :disappointed:

**Comment by gromenauer** [comment]
https://github.com/yuru-yuri/manga-dl/blob/bb743ec39aa64afd28ca78066250a84185e45bb6/manga_py/base_classes/base.py#L166

The [bitwise invert operator](https://docs.python.org/3/reference/expressions.html#unary-arithmetic-and-bitwise-operations) `~` seems strange to me there. Maybe you want to use the [boolean-operator](https://docs.python.org/3/reference/expressions.html#boolean-operations) `not` ?

**Comment by gromenauer** [comment]
~~~ bash
manga-py --cbz --zero-fill --rename-pages --destination Manga/ http://mangalife.us/manga/For-My-Daughter
~~~ 
works OK

**Comment by 1271** [comment]
> Bitwise inverting operator ~ seems strange to me

Not.
'string'.find ('s') == 0
'string'.find ('x') == -1

~ (-1) = 0
~ 0 = -1

Profit =)

It would be more logical to compare it to -1. But it was decided to abandon it.
