### ISSUE TITLE
Can't install version 1.2.1.3

### ISSUE THREAD

**Issue by MercuryxLion** [yuru-yuri/manga-dl#54]
I can't install the latest version of manga-py, after executing 

**pip install manga-py**

It gives me this output:

**No files/directories in /tmp/pip-build-xm8s_2lp/manga-py/pip-egg-info (from PKG-INFO)**

**Comment by gromenauer** [comment]
Tried this way and it works for me: 
~~~ bash
pip install pipenv --upgrade --user
mkdir ~/test
cd ~/test
pipenv shell
pip install manga-py
# Work with manga-py
exit

# To use it again
cd ~/test # To use the Pipfile created
pipenv shell
# Work with manga-py
exit # To exit the virtualenv
~~~

[pipenv](https://docs.pipenv.org/) is the new recommended way to use virtualenvs.

**Comment by yunomi** [comment]
that seems to not work either.
I still get the same error as MercuryxLion

**Comment by 1271** [comment]
Hmmm...

I tryed here on Ubuntu and Windows. All ok for me 
![image](https://user-images.githubusercontent.com/1452243/41456321-baef2f98-7088-11e8-8762-b8a52ec581d1.png)

**Comment by 1271** [comment]
Try install it like this:
```
python3 -mpip install manga-py
```
It works?

**Comment by yunomi** [comment]
![installfailed](https://user-images.githubusercontent.com/21093528/41476990-101eb3c8-7091-11e8-96c3-b9efecb77958.png)

I tried installing it the way you said.
The attached image is the result.

I'm using Windows 10 + Python 3.7 + GitBash

**Comment by 1271** [comment]
Try clear cache folder and reinstall it. (Remove folder %AppData/Local/Temp/pip-install-ba9zb3tk )

**Comment by 1271** [comment]
> I've tried installing an earlier version (1.2.0.1), but it throws a wall of errors too.

All versions are checked before unloading. This should work.
Perhaps you have not established any dependence.

Please, try downloading [requirements.txt](https://raw.githubusercontent.com/yuru-yuri/manga-dl/master/requirements.txt) and run command:
```
pip install -r requirements.txt
```
Does this cause a error?

**Comment by 1271** [comment]
Try clear cache folder and reinstall it. (Remove folder %AppData/Local/Temp/pip-install-ba9zb3tk )
And try use [Anaconda](https://www.anaconda.com/download/)

Because it worked for my and other people.

---

There is another idea. Try using python 3.5 or 3.6
If it works, I'll look for an error for version 3.7

---

> I've tried installing an earlier version (1.2.0.1), but it throws a wall of errors too.

All versions are checked before unloading. This should work.
Perhaps you have not established any dependence.

Please, try downloading [requirements.txt](https://raw.githubusercontent.com/yuru-yuri/manga-dl/master/requirements.txt) and run command:

pip install -r requirements.txt
Does this cause a error?

**Comment by 1271** [comment]
Hello, @MercuryxLion, @gromenauer, @yunomi
Nothing is heard from you. Did it work for you?

**Comment by yunomi** [comment]
@1271 I'll check this out by running on my surface pro later (It has Anaconda installed)
I'll let you know when I am done.

**Comment by 1271** [comment]
If you can not install manga-py from pip, you can always work with its "repository" version.

Like that:

_Installation:_
```bash
git clone https://github.com/yuru-yuri/manga-dl.git
pip install -r manga-dl/requirements.txt
```

_Usage:_
```bash
python manga-dl/manga.py http://example.org/manga/url/here
```

**Comment by yunomi** [comment]
I Installed cloned it and installed the requirements.
I try to make it work but I think I don't understand how the commands work
![failed](https://user-images.githubusercontent.com/21093528/41622818-c9c11834-73de-11e8-867c-92697d697fb6.png)

**Comment by 1271** [comment]
> I Installed cloned it and installed the requirements.

Message `setup in progress?` means for you that not all requirements have been set.

Please update your version of manga-py with the command:
git pull

The next run will tell you which module is required.
Please let me know what is missing.

**Comment by 1271** [comment]
You wrote:
> I'm using Windows 10 + Python 3.7 + GitBash

You wrote that you use conda.
But I see that it does not have version 3.7:
![2018-06-20-090930_485x565_scrot](https://user-images.githubusercontent.com/1452243/41640280-d7b01f5e-7469-11e8-9d0d-1c8df29a047e.png)

**Comment by yunomi** [comment]
This is what I got when I do a Git pull, and then try to update/install the missing package is tells me to.
`yunomi@DESKTOP-TRK7OI6 MINGW64 ~/Desktop/github_mangaDLer/manga-dl (master)
$ git pull https://github.com/yuru-yuri/manga-dl.git
remote: Counting objects: 58, done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 58 (delta 41), reused 52 (delta 37), pack-reused 2
Unpacking objects: 100% (58/58), done.
From https://github.com/yuru-yuri/manga-dl
 * branch            HEAD       -> FETCH_HEAD
Updating 7197d29..1595a80
Fast-forward
 manga_py/__init__.py                     | 18 ++++++--
 manga_py/base_classes/archive.py         | 34 +++++++-------
 manga_py/base_classes/base.py            | 13 +++---
 manga_py/cli.py                          | 27 ++++++-----
 manga_py/http/__init__.py                | 35 +++++++++------
 manga_py/http/request.py                 |  2 +-
 manga_py/image.py                        |  8 ++++
 manga_py/info.py                         | 13 +++++-
 manga_py/meta.py                         |  2 +-
 manga_py/provider.py                     | 26 ++++++-----
 manga_py/providers/__init__.py           | 13 ++++++
 manga_py/providers/danbooru_donmai_us.py |  4 +-
 manga_py/providers/helpers/std.py        |  2 +-
 manga_py/providers/leitor_net.py         | 77 ++++++++++++++++++++++++++++++++
 manga_py/providers/lolibooru_moe.py      |  4 +-
 manga_py/providers/truyenchon_com.py     | 41 +++++++++++++++++
 manga_py/providers/yande_re.py           |  8 ++++
 17 files changed, 257 insertions(+), 70 deletions(-)
 create mode 100644 manga_py/providers/leitor_net.py
 create mode 100644 manga_py/providers/truyenchon_com.py
 create mode 100644 manga_py/providers/yande_re.py

yunomi@DESKTOP-TRK7OI6 MINGW64 ~/Desktop/github_mangaDLer
$ python manga-dl/manga.py https://tonarinoyj.jp/episode/10834108156631093439 ~/manga
No module named 'packaging'
Setup in progress?

yunomi@DESKTOP-TRK7OI6 MINGW64 ~/Desktop/github_mangaDLer
$ pip install packaging
Collecting packaging
  Using cached https://files.pythonhosted.org/packages/ad/c2/b500ea05d5f9f361a562f089fc91f77ed3b4783e13a08a3daf82069b1224/packaging-17.1-py2.py3-none-any.whl
Collecting pyparsing>=2.0.2 (from packaging)
  Using cached https://files.pythonhosted.org/packages/6a/8a/718fd7d3458f9fab8e67186b00abdd345b639976bc7fb3ae722e1b026a50/pyparsing-2.2.0-py2.py3-none-any.whl
Collecting six (from packaging)
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Installing collected packages: pyparsing, six, packaging
Successfully installed packaging-17.1 pyparsing-2.2.0 six-1.11.0

yunomi@DESKTOP-TRK7OI6 MINGW64 ~/Desktop/github_mangaDLer
$ python manga-dl/manga.py https://tonarinoyj.jp/episode/10834108156631093439 ~/manga
No module named 'progressbar'
Setup in progress?

yunomi@DESKTOP-TRK7OI6 MINGW64 ~/Desktop/github_mangaDLer
$ pip install manga-dl/requirements.txt
Invalid requirement: 'manga-dl/requirements.txt'
Traceback (most recent call last):
  File "c:\users\yunomi\new folder\lib\site-packages\pip\_vendor\packaging\requirements.py", line 93, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "c:\users\yunomi\new folder\lib\site-packages\pip\_vendor\pyparsing.py", line 1632, in parseString
    raise exc
  File "c:\users\yunomi\new folder\lib\site-packages\pip\_vendor\pyparsing.py", line 1622, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "c:\users\yunomi\new folder\lib\site-packages\pip\_vendor\pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "c:\users\yunomi\new folder\lib\site-packages\pip\_vendor\pyparsing.py", line 3395, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "c:\users\yunomi\new folder\lib\site-packages\pip\_vendor\pyparsing.py", line 1383, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "c:\users\yunomi\new folder\lib\site-packages\pip\_vendor\pyparsing.py", line 3183, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pip._vendor.pyparsing.ParseException: Expected stringEnd (at char 8), (line:1, col:9)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\yunomi\new folder\lib\site-packages\pip\_internal\req\req_install.py", line 252, in from_line
    req = Requirement(req)
  File "c:\users\yunomi\new folder\lib\site-packages\pip\_vendor\packaging\requirements.py", line 97, in __init__
    requirement_string[e.loc:e.loc + 8]))
pip._vendor.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "'/require'"


yunomi@DESKTOP-TRK7OI6 MINGW64 ~/Desktop/github_mangaDLer
$ pip install progeressbar
Collecting progeressbar
  Could not find a version that satisfies the requirement progeressbar (from versions: )
No matching distribution found for progeressbar
`

Also, Anaconda is on the laptop I'm using, Python is on my Desktop.
Right now I'm testing it on my Laptop.

**Comment by 1271** [comment]
> $pip install manga-dl/requirements.txt

Syntax error!
This is used like this:

pip install **-r** manga-dl/requirements.txt

Also I see that you do not have a progeressbar installed.

Please try the version of python 3.5 or 3.6

**Comment by 1271** [comment]
See also https://github.com/yuru-yuri/manga-dl/issues/57
Maybe it help for you.

**Comment by 1271** [comment]
This issue will be closed, because there is no reaction from you.
If the situation is relevant, return the state "open" by clicking the button below.
