### ISSUE TITLE
jpg renamed as png

### ISSUE THREAD

**Issue by gromenauer** [yuru-yuri/manga-dl#55]
Tried:

~~~ bash
manga-py --cbz --zero-fill --rename-pages --destination ~/Manga/ http://mangalife.us/manga/Yuusha-Ga-Shinda
~~~

Failed in `vol_004-0.cbz` all files inside are `*.png`, but I have to rename it as `*.jpg` in order to view it.

In this case the extension is wrong in the origin.  
Should it be too much overhead to [detect the format](https://pillow.readthedocs.io/en/latest/reference/Image.html#PIL.Image.format)?

**Comment by 1271** [comment]
As I see, on the page all the same the files are png, not jpg:

```
<div class="image-container" style="margin-bottom:5px;">
	<a href="/read-online/Yuusha-Ga-Shinda-chapter-130-page-2.html"><img class="CurImage" src="http://93.190.142.23/manga/Yuusha-Ga-Shinda/0130-001.png"></a>		
</div>
```

**Comment by gromenauer** [comment]
`manga-py` can't discover the file format now.
You could use:
~~~ python
from PIL import Image
img = Image.open(filename)
print(img.format)  # 'JPEG'
~~~

**Comment by 1271** [comment]
Yes, I know about this opportunity. But what's the point in it, if more than 95% of images obtained from sites have an extension?
And koreektnoe.

If the site gives the image as image.png, it's PNG. Not JPEG.

**Comment by 1271** [comment]
And....
Ok, I'll add this functionality, but with the launch flag. :innocent:
Will that suit you?

**Comment by gromenauer** [comment]
Happy to help :smile: 

English is hard to me too.
I have edited responses too many times, after realizing what people really mean.

**Comment by 1271** [comment]
You original language ?

**Comment by 1271** [comment]
Done! I have correct result now.
![image](https://user-images.githubusercontent.com/1452243/41626305-9fc17be6-743d-11e8-885e-e92665ab6560.png)

**Comment by gromenauer** [comment]
Works OK
(It gives a 403 Error many times, because the page is broken)

**Comment by gromenauer** [comment]
My original language is Spanish == Mi lenguaje original es Español.

**Comment by 1271** [comment]
> It gives a 403 Error many times
Try usage `-np` option. This should help.
Some sites limit the number of simultaneous download streams.

> Spanish
Ok, amigo =)
