### ISSUE TITLE
Mangarock.com, some doubts and Suggestions.

### ISSUE THREAD

**Issue by phanirithvij** [yuru-yuri/manga-dl#58]
# Issues
For [mangarock.com](https://mangarock.com/)
The **get_manga_name** function in [mangarock_com.py](https://github.com/yuru-yuri/manga-dl/blob/master/manga_py/providers/mangarock_com.py) needs to be updated, as the output is not the manga name.
It's **mrs-serie** for every manga.
#### Screenshot:
![mrs-serie](https://user-images.githubusercontent.com/29627898/41733144-9e99e5f0-75a0-11e8-9ad7-01985d11781e.png)

# Doubts
How long did it take to **plan** this project?
How long did it take to **code** this project?

# Sugessions
I don't know if people like reading manga in pdf format but check this out [kissmanga-pdf-downloader](https://github.com/pratikhit07/kissmanga-pdf-downloader)

#### Not promoting this. !!!
**[kissmanga-pdf-downloader](https://github.com/pratikhit07/kissmanga-pdf-downloader)** is **not written by me** or I don't really know the one who wrote it except his username and I am **not promoting it**.

**Comment by 1271** [comment]
Hello. The project was conceived for personal use.
But after a while, I decided to make it public.
What was originally planned was greatly changed. Version 1.0 has appeared.
The project will soon be a year. The time for planning the architecture as a whole was spent about a couple of days. Although later, as already wrote, much has changed in it.

Initially, for each site was written a separate script. And about three sites were supported.

As for the name of the manga - for most providers, the name is taken from the url. This is simpler and ensures that the directory name does not change.
In any case, you can always insert your name using the --name option.

As for the pdf format - most readers like the archive with the files.
I believe that pdf is not the best format. Especially for reading manga.

If you have any suggestions for improvement, you can freely express them.
If something does not suit you in manga-py, it's your right.
The software is delivered "as is". The project does not in any way pretend to be uniqueness or the title of "best". And written by an amateur. =)
Python is not my main programming language. I studied with the project.

Surely, there are many things that need to be improved, but at the moment there is no time for it and, perhaps, my knowledge.

**Comment by 1271** [comment]
> It's mrs-serie for every manga.

Thanks for the remark about kissmanga 👍 . This will be fixed soon. My mistake.

**Comment by 1271** [comment]
> It's mrs-serie for every manga.

Thanks for the remark about kissmanga 👍 . This will be fixed soon. My mistake.

The site changed the routing.

Unfortunately, it is difficult to follow all the changes alone.

I am very grateful to everyone who points out mistakes.

**Comment by 1271** [comment]
> It's mrs-serie for every manga.

Thanks for the remark about mangarock👍 . This will be fixed soon. My mistake.

**Comment by 1271** [comment]
Please, check now.

**Comment by phanirithvij** [comment]
Thanks.
I'm closing the issue.
