### ISSUE TITLE
Mangaeden Not available in your country ERROR

### ISSUE THREAD

**Issue by phanirithvij** [yuru-yuri/manga-dl#61]
I'm from __India__ so there are useless restrictions

# Mangaeden says

#### Screen Shot of [One piece 908](https://www.mangaeden.com/en/en-manga/one-piece/908/1/)

![mangaedenerr](https://user-images.githubusercontent.com/29627898/41806599-97cb0eea-76de-11e8-8e7c-144fa58dcad3.png)

## But they have an API

To get that particular chapter images

https://www.mangaeden.com/api/chapter/5b2395bc719a1624d6c40514/

<details>
<summary>Detailed ..</summary>
<br>

### Manga details eg.
https://www.mangaeden.com/api/manga/4e70ea10c092255ef7004aa2/

### Chapter details eg.
https://www.mangaeden.com/api/chapter/5b2395bc719a1624d6c40514/

### Image url eg.
https://cdn.mangaeden.com/mangasimg/200x/09/098f22767af2c22e8b6948624820f761a2eac8f085391fe4f141b885.jpg

</details>
<br>

And I don't think you're using their API

[Mangaeden API](https://www.mangaeden.com/api/)

But their API doesn't check for countries and restrictions
So it's possible to avoid that country issue 

But they don't have a direct __get manga details by name__  API method

They do have a search results API method 
[Search by Name of Manga](https://www.mangaeden.com/ajax/search-manga/?term=one+piece)

So I'm guessing you could add **future** tag to this issue and implement it?

**Comment by gromenauer** [comment]
What other people do in this case is use a proxy, usually tor and set the output node to a specific country.

**Comment by phanirithvij** [comment]
### So should I just close the issue?

**Comment by gromenauer** [comment]
If it's solved for you I think that you could close it, if @1271 wants to work more he can reopen it and label it as **future** work

If not, you could try `--proxy` with tor or with one of the proxies of the list in https://free-proxy-list.net/ (Seen in https://www.scrapehero.com/how-to-rotate-proxies-and-ip-addresses-using-python-3/) and tell here if this solves it to you.

**Comment by phanirithvij** [comment]
Okay then.

**Comment by 1271** [comment]
Please, check latest commit. Its worked! =)
