### ISSUE TITLE
Isekai ni kita mitai dakedo ikanisureba yoi no darou

### ISSUE THREAD

**Issue by gromenauer** [yuru-yuri/manga-dl#63]
Tried:
~~~ bash
manga-py --cbz --zero-fill --rename-pages --destination Manga/ http://www.mangago.me/read-manga/isekai_ni_kita_mitai_dakedo_ikanisureba_yoi_no_darou/
~~~
Output:
~~~
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/providers/mangago_me.py", line 8, in get_archive_name
    idx = self.get_chapter_index().split('-')
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/providers/mangago_me.py", line 15, in get_chapter_index
    idx = self.re.search(selector, chapter).groups()
~~~

Tried:
~~~ bash
manga-py --cbz --zero-fill --rename-pages --destination Manga/ https://mangapark.me/manga/m5a33f69ee2ed8
~~~
Output:
~~~
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/providers/mangapark_me.py", line 8, in get_archive_name
    idx = self.get_chapter_index().split('-')
  File "~/.local/share/virtualenvs/0_bin-S-IZrhuG/lib/python3.5/site-packages/manga_py/providers/mangapark_me.py", line 15, in get_chapter_index
    1 if idx[0] is None else idx[0],
~~~

Tried the same with:

| Url | Result|
| --- | ---|
|http://www.mangahere.cc/manga/isekai_ni_kita_mitai_dakedo_ikaga_sureba_yoi_no_darou/ | no output nor files |
|http://mangakakalot.com/manga/isekai_ni_kita_mitai_dakedo_ikanisureba_yoi_no_darou |no output nor files|
|http://mangahasu.se/isekai-ni-kita-mitai-dakedo-ikanisureba-yoi-no-darou-p28772.html |  `raise AttributeError('Provider not found')`|
|https://www.niadd.com/manga/ISEKAI+NI+KITA+MITAI+DAKEDO+IKAGA+SUREBA+YOI+NO+DAROU.html |  `raise AttributeError('Provider not found')`|
|http://mangaon.net/ | "Sorry, Site is closed"|
|http://www.mangatrue.com/|Server not found|
|https://mangarock.com/manga/mrs-serie-100143997|~Eureka! Works OK~ Weird page format `000.mri.webp` |
|http://ninemanga.com/manga/Isekai+ni+Kita+Mitai+dakedo+Ikanisureba+Yoi+no+Darou.html|Works! (Strange directory name with `+` instead of spaces, but works)|

**Comment by 1271** [comment]
It uses one provider. Please wait for the update. This will be fixed.

**Comment by 1271** [comment]
> https://www.niadd.com/manga/ISEKAI+NI+KITA+MITAI+DAKEDO+IKAGA+SUREBA+YOI+NO+DAROU.html

This is not supported yet.
Will be added soon.

(For sites that are not on the list https://yuru-yuri.github.io/manga-dl/, it's best to make a separate ISSUE, please.)
So it will be easier. Thank you.

**Comment by 1271** [comment]
In any case, you need to wait for version 1.3.0.

There will be fixed a lot and added (most likely) support `--update-all`

**Comment by 1271** [comment]
UPD:

Oh my god ... mangago maniacs.
Just check out:
http://www.mangago.me/read-manga/isekai_ni_kita_mitai_dakedo_ikanisureba_yoi_no_darou/nbt/b54fbd0c620a8d14/Vol1_Ch1/
http://www.mnggo.net/article/how-to-choose-a-hair-dryer,1671.html

This is the same address.
How are you?

In any case, thanks for ISSUE.

I will correct.

**Comment by 1271** [comment]
My browser pins very crazy... 😞 
![image](https://user-images.githubusercontent.com/1452243/41836574-cf4d0662-7863-11e8-9e25-ce0d32913efd.png)

**Comment by 1271** [comment]
With mangago, everything is complicated. They entered encryption for addresses.
I'm working on it. There are several more projects that have encountered this problem.
You need to wait.

Thank you for understanding.

**Comment by 1271** [comment]
> http://ninemanga.com/manga/Isekai+ni+Kita+Mitai+dakedo+Ikanisureba+Yoi+no+Darou.html

The web is generally strange. And yes, there is no space character in it. Instead, it uses `+` or `%20`.
I usually do not replace `+` with a space. But since the question arose, this behavior will be changed.

> https://mangarock.com/manga/mrs-serie-100143997

`webp` is the normal image format.
Unfortunately, at the moment the function of converting images to png format is disabled.
It will be returned in the future.

Please use a graphic editor or image viewer on your PC to change the format. (For example, ACDsee or XnView)
They are able to change the format of all images in the folder.

> http://www.mangatrue.com/

This error is not in manga-py. Thank you, I will make a note.


> http://www.mangahere.cc/manga/isekai_ni_kita_mitai_dakedo_ikaga_sureba_yoi_no_darou/
> http://mangakakalot.com/manga/isekai_ni_kita_mitai_dakedo_ikanisureba_yoi_no_darou

Thank you! This is fixed in version 1.3.0.3-alpha

**Comment by 1271** [comment]
Oh my God...
http://mangahasu.se/suijin-no-ikenie-p21111.html
Its routing really crazy!

**Comment by 1271** [comment]
Its worked now!
Please, check version >= 1.3.1.0
