### ISSUE TITLE
Number names in rawqv.com

### ISSUE THREAD

**Issue by gromenauer** [yuru-yuri/manga-dl#66]
Doing:
~~~ bash
manga-py --cbz --zero-fill --rename-pages --destination Manga/ https://rawqv.com/manga-tensei-shi-chatta-yo-iya-gomen.html --reverse-downloading
~~~
Got this files:
~~~
vol_001-9.cbz
vol_001-8.cbz
...
~~~
The name should be (I think):
~~~
vol_019-0.cbz
vol_018-0.cbz
...
~~~

**Comment by gromenauer** [comment]
@1271 please don't work in excess solving issues. Do it while is fun, when you have time.
(Lots of projects die when it's no fun anymore).

**Comment by 1271** [comment]
Thank you for the issue.
Do not worry. If I get tired of this project, then I'm tired of manga.
And I do not intend to refuse the manga.

**Comment by gromenauer** [comment]
Works OK. Thanks!
