### ISSUE TITLE
bato.to page order

### ISSUE THREAD

**Issue by gromenauer** [yuru-yuri/manga-dl#67]
Pages extracted from bato.to came out in the wrong order.

Tried:
~~~ bash
manga-py --cbz --zero-fill --rename-pages --destination Manga/ https://bato.to/series/68464
~~~
Second page is `011.png`
Third page is `022.png`
...

**Comment by 1271** [comment]
Hi. Please, try:
` --ename-pages` -> ` --rename-pages` :smile:

**Comment by 1271** [comment]
One moment more.

**Comment by 1271** [comment]
Thanks for the issue!
My mistake.
Check new version, please.

**Comment by gromenauer** [comment]
Works OK :+1:
