### ISSUE TITLE
hatigarmscans not supported

### ISSUE THREAD

**Issue by gromenauer** [yuru-yuri/manga-dl#68]
In https://manga-dl.yuru-yuri.sttv.me/ i see listed
~~~
☑  http://hatigarmscans.eu
☑  http://hatigarmscans.net 
~~~

Tried with https://www.hatigarmscans.net/manga/guild-no-cheat-na-uketsukejou but I get:
~~~
    raise AttributeError('Provider not found')
~~~

**Comment by 1271** [comment]
The routing has changed.

Hey. Thanks for the issue!
Check it out in the new version, please.

**Comment by gromenauer** [comment]
works OK :+1:
