### ISSUE TITLE
Handling web redirections

### ISSUE THREAD

**Issue by gromenauer** [yuru-yuri/manga-dl#69]
From time to time manga webs redirect their domains as they need to. (Can the user do anything about it?)

This webs are examples:
* http://heavenmanga.biz 
* http://heavenmanga.site
* http://heavenmanga.world 

are now redirected to http://heavenmanga.life/ , if you don't know and provide a ur to `manga-py` then you get:
~~~
raise AttributeError('Provider not found')
~~~

**Comment by 1271** [comment]
Hey. Unfortunately, nothing can be done about this.
Some manga sites have the same second-level domain, but these are different sites:

readmanga.me
readmanga.eu

There are a few more examples.

I'm grateful for the issue.

This will work for manga-py version 2.x

---

Hey. Thanks for the issue!
Check it out in the new version, please.

**Comment by 1271** [comment]
Thank you.

**Comment by gromenauer** [comment]
http://heavenmanga.biz/isekai-ni-tensei-shitara-zenra-ni-sareta/ works ok in 1.3.3 :+1:
