### ISSUE TITLE
goodmanga.net gets only one image

### ISSUE THREAD

**Issue by gromenauer** [yuru-yuri/manga-dl#70]
Tried:
~~~
manga-py --cbz --zero-fill --rename-pages --destination Manga/ http://goodmanga.net/14569/atrail-nisekawiteki-nichijou-to-senmitsu-element
~~~
Got two archives, lots of pages, but all pages are equal to the first page of the archive.

**Comment by 1271** [comment]
Hey. Thanks for the issue!
My mistake.
Check new version, please.

**Comment by gromenauer** [comment]
~~~ bash
manga-py --version
1.3.2
~~~
Tried again, it improves, but now only gets the first page.

**Comment by 1271** [comment]
Ohh.. Sorry.
Thank you.

**Comment by gromenauer** [comment]
works OK in 1.3.3 :+1:
