### ISSUE TITLE
mangahere.cc pages duplicated

### ISSUE THREAD

**Issue by gromenauer** [yuru-yuri/manga-dl#72]
Tried (version 1.3.3) :
~~~
manga-py --cbz --zero-fill --rename-pages --destination Manga/ http://www.mangahere.cc/manga/goodbye_isekai_tensei/
~~~
Downloads everything, but duplicates the pages.

`vol_001-0.cbz`:
* `002.jpg` == `071.jpg`
* `003.jpg` == `072.jpg`
* `004.jpg` == `073.jpg`
* ...

**Comment by 1271** [comment]
Try new version. (1.3.4)

**Comment by gromenauer** [comment]
Works OK with 1.3.4 
Thanks for your hard work! :medal_sports:
