### ISSUE TITLE
Add Mang.as (Spanish) Provider

### ISSUE THREAD

**Issue by phanirithvij** [yuru-yuri/manga-dl#73]
Add [Mang.as](https://mang.as) 
It's the same as [Zmanga](https://zmanga.net)

I't exactly the same but

_Note that I just found out that such site exists and am informing you_

_**I Don't Know Spanish**_

**Comment by 1271** [comment]
Not problem! Thanks!

**Comment by gromenauer** [comment]
Works OK with 1.3.6 :+1:
