### ISSUE TITLE
mangasail.com volume order

### ISSUE THREAD

**Issue by gromenauer** [yuru-yuri/manga-dl#74]
Tried (version 1.3.4) :
~~~
manga-py --cbz --zero-fill --rename-pages --destination Manga/ Site: http://www.mangasail.com/content/ore-no-ie-ga-maryoku-spot-datta-ken-%E2%80%93-sundeiru-dake-de-sekai-saikyou
~~~
Downloads OK, but volumes are not in order:
~~~
vol_000-5.cbz
vol_001-4.cbz
vol_002-3.cbz
vol_003-2.cbz
vol_004-1.cbz
~~~
The correct order (with this names):
~~~
vol_004-1.cbz
vol_003-2.cbz
vol_002-3.cbz
vol_001-4.cbz
vol_000-5.cbz
~~~

**Comment by 1271** [comment]
Thank you.
The order was changing. at that time on the site was the wrong order of the chapters.
Will be fixed soon.

**Comment by gromenauer** [comment]
Works OK with 1.3.6
Fixes http://www.mangahere.cc too.

Not sure hoducomics.com it's working, not english, I have no clue.

**Comment by 1271** [comment]
> Not sure hoducomics.com it's working

Working =)
But use https://hodu1.com

**Comment by gromenauer** [comment]
Sure? Out of curiosity (I cant read it) I have tried:
~~~ bash
manga-py --cbz --zero-fill --rename-pages --destination Manga/ https://hodu1.com/webtoon/list/458
~~~
Prints html to console, but downloads nothing !?!

**Comment by 1271** [comment]
Oh. I did not clean up the debugging. Thank you. This is deleted now.
If the download does not work, try to specify the folder name explicitly:

```
manga-py --cbz --zero-fill --rename-pages -d ~/Manga https://hodu1.com/webtoon/list/458 -n SexyChicks
```

I'll check it out for a few more PCs soon.
If it does not upload images, I will open a new issue.

**Comment by gromenauer** [comment]
This goes OK:
~~~ bash
mkdir -p ~/Manga/
manga-py --cbz --zero-fill --rename-pages -d ~/Manga/ https://hodu1.com/webtoon/list/458 -n SexyChicks
~~~

But this not
~~~ bash
mkdir -p ~/Manga/Manga/Manga/
manga-py --cbz --zero-fill --rename-pages -d ~/Manga/Manga/Manga/ https://hodu1.com/webtoon/list/458 -n SexyChicks
~~~
strange bug.

**Comment by 1271** [comment]
> strange bug.

Can you send an error message?

P.S. you do not have to create the folders yourself. manga-py does this for you.

**Comment by 1271** [comment]
I fixed it. Thanks!
