### ISSUE TITLE
New providers MangaX, MangaWindow

### ISSUE THREAD

**Issue by phanirithvij** [yuru-yuri/manga-dl#75]
# [MangaX](http://www.mangax.net)
# [MangaWindow](https://mangawindow.net/)
# [MangaPark.ORG](https://mangapark.org/)

### Image:

[Image link](http://s1.mgimgcdn.com/r1/read_one_piece_manga_online_free4/chapter_908_the_riverie_begins/3.jpg)

**Comment by phanirithvij** [comment]
Both use **Jaiminisbox's** images for One Piece (I guess you know One piece).

But as Jaiminisbox is limited to around 50 ( I think so ) mangas

It's not bad to implement them

**Comment by 1271** [comment]
Thank you. Will be added in the next update.

**Comment by gromenauer** [comment]
MangaX works OK with 1.3.7 :+1:
