### ISSUE TITLE
One more Provider Mangareader.XYZ

### ISSUE THREAD

**Issue by phanirithvij** [yuru-yuri/manga-dl#76]
# [Mangareader.xyz](http://mangareader.xyz/)

A provider that's not in your list but almost implemented it (I think so)

![mangareader](https://user-images.githubusercontent.com/29627898/42221623-4f3c75d2-7ef0-11e8-88ed-fced000983ae.png)

### Another One

# [MyMangaList](http://www4.mymangalist.org/chapter-bleach-686)

**Comment by phanirithvij** [comment]
They use **mangastream**'s images so I don't think it's that famous
But just to let you know such site exists

**Comment by 1271** [comment]
Thank you. Will be added in the next update.
