### ISSUE TITLE
Some more providers MangaMew, MangaHi

### ISSUE THREAD

**Issue by phanirithvij** [yuru-yuri/manga-dl#77]
# [MangaMew](https://www1.mangamew.com/)

## It kind of imitates MangaRock

# [MangaHi](https://mangahi.net/)

**Comment by 1271** [comment]
Thank you. Will be added in the next update.

**Comment by gromenauer** [comment]
Works in 1.3.7 :+1:

**Comment by richyhill** [comment]
Idk how to use this app at all
