### ISSUE TITLE
8muses.com volume and page order

### ISSUE THREAD

**Issue by gromenauer** [yuru-yuri/manga-dl#79]
Tried (with version 1.3.5): 
~~~
manga-py --cbz --zero-fill --rename-pages --destination ~/Manga/ https://www.8muses.com/comics/album/BroadSword-Comics/Tarot-Witch-of-the-Black-Rose/
~~~
It starts downloading the last volume:
~~~
vol_BroadSword-Comics-Tarot-Witch-of-the-Black-Rose-Tarot-Witch-of-the-Black-Rose-060.cbz
vol_BroadSword-Comics-Tarot-Witch-of-the-Black-Rose-Tarot-Witch-of-the-Black-Rose-059.cbz
vol_BroadSword-Comics-Tarot-Witch-of-the-Black-Rose-Tarot-Witch-of-the-Black-Rose-058.cbz
...
~~~
The pages are in the wrong order. vol_...-060.cbz :
~~~
000.jpg
002.jpg
001.jpg
003.jpg
004.jpg
006.jpg
...
~~~

**Comment by 1271** [comment]
I will check it. Thanks for the issue

**Comment by 1271** [comment]
Done! Wait for version 1.3.6.

**Comment by gromenauer** [comment]
Tried version 1.3.6:
* Downloads (almost) OK :+1: 
* Starts downloading backwards `vol_BroadSword-Comics-Tarot-Witch-of-the-Black-Rose-Tarot-Witch-of-the-Black-Rose-060.cbz` first :confused: 
* In `vol_BroadSword-Comics-Tarot-Witch-of-the-Black-Rose-Tarot-Witch-of-the-Black-Rose-060.cbz` downloads beyond last page and is a duplicate (`037.jpg` == `001.jpg`) :confused:

**Comment by 1271** [comment]
Lol =)
The site does issue two duplicate images.
Thank you. I will fix it.
