### ISSUE TITLE
No error when the disk is full

### ISSUE THREAD

**Issue by gromenauer** [yuru-yuri/manga-dl#80]
Try this with your disk full except 200k (1M?) (maybe in a virtual machine):
~~~ bash
manga-py --cbz --zero-fill --rename-pages https://freemanga.to/manga/read-overlord-manga
~~~
cbz created with no error.

**Comment by 1271** [comment]
I do not check the available space. But this is a good idea. Thank you!

**Comment by 1271** [comment]
Default value = 100M

`--min-free-space` param

**Comment by gromenauer** [comment]
It works :+1:
