### ISSUE TITLE
mangago encryption

### ISSUE THREAD

**Issue by 1271** [yuru-yuri/manga-dl#82]
Need solve matrix.
Image examples:

---

![image](https://user-images.githubusercontent.com/1452243/42309433-3b076cf0-8041-11e8-8554-3c61b32e0d00.png)
![image](https://user-images.githubusercontent.com/1452243/42309446-408ad306-8041-11e8-831e-35755156342c.png)

---

![image](https://user-images.githubusercontent.com/1452243/42309454-45ba4226-8041-11e8-9e5d-d6535c80bf21.png)
![image](https://user-images.githubusercontent.com/1452243/42309461-4845f58a-8041-11e8-976c-0064f04f6b3d.png)

---

Link examples:
Enc:
http://iweb7.mangapicgallery.com/r/cspiclink/lookism/443703/dbdf873a11bafad56c41ff7fbed622aa76e19f3564e5d52a6688d6d9e3c57fb2.jpeg
Not enc:
http://iweb7.mangapicgallery.com/r/newpiclink/lookism/188/092627e2b8795ced4cb3e80ff189b972.jpeg

**Comment by 1271** [comment]
You also need to decrypt the variable **imgsrcs**.
Link example: www.mnggo.net/c/23177/443703/1/

**Comment by phanirithvij** [comment]
How did you find that the site has **Lookism** in it?

**Comment by 1271** [comment]
Just see the list of forbidden resources for the site.
You will see used js / css / jpg files.

**Comment by 1271** [comment]
Solved on kotlin:
https://github.com/inorichi/tachiyomi-extensions/blob/master/src/en/mangago/src/eu/kanade/tachiyomi/extension/en/mangago/Mangago.kt

**Comment by 1271** [comment]
Solved:
https://codepen.io/1271/pen/mKYLrG
