### ISSUE TITLE
Mangafox.CC request for a new provider

### ISSUE THREAD

**Issue by phanirithvij** [yuru-yuri/manga-dl#83]
# [MangaFox.CC](http://mangafox.cc/)

Another source

**Comment by 1271** [comment]
Check the new version.
Please close the issue if it's okay.

**Comment by phanirithvij** [comment]
# It works great
## But I have a doubt

**Is it always in every website the the downloads start from chapter 0 (or 1)**

**Comment by 1271** [comment]
> Is it always in every website the the downloads start from chapter 0 (or 1)

No. Sometimes on a site spread chapters, since the middle.
The index of chapters in most cases is taken real. With a few exceptions, when this is impossible, or very difficult to implement.

**Comment by 1271** [comment]
Try to get this manga:
http://mangafox.cc/manga/chunqing-yatou-huolala

Here are skipped chapters from 44 to 111, from 113 to 171 and from 192 to 234.

You can use the `-s` option to skip as many chapters as you need.

```
manga-py http://mangafox.cc/manga/chunqing-yatou-huolala -s 60
```

Try it! =)
