### ISSUE TITLE
Bug in fanfox.net provider

### ISSUE THREAD

**Issue by gromenauer** [yuru-yuri/manga-dl#95]
Tried in `1.3.18`:
~~~ bash
pipenv run manga-py --cbz --zero-fill --rename-pages --destination Manga/ http://fanfox.net/manga/isekai_de_kuro_no_iyashi_te_tte_yobarete_imasu/
~~~

It downloaded:
~~~
vol_c001-0.cbz
vol_c002-0.cbz
...
vol_c017-0.cbz
vol_c018-0.cbz
vol_c020-0.cbz
vol_c020-5.cbz
vol_v01-0.cbz
vol_v02-0.cbz
vol_v03-0.cbz
vol_v04-0.cbz
~~~

Are missing 21 to 30 and 19 chapters, while 1 to 4 are duplicate.

**Comment by 1271** [comment]
I changed the name generation. Please check now.

Unfortunately, some of the chapters are not sorted.
So I added a non-significant 0 at the end. (In case the chapter does not contain an additional index):

Before:
![image](https://user-images.githubusercontent.com/1452243/43702792-81c603f0-9963-11e8-8211-c4639402e44e.png)

After:
![image](https://user-images.githubusercontent.com/1452243/43702807-8d42cff6-9963-11e8-8c30-7339b93179f4.png)

**Comment by 1271** [comment]
Please, check version `1.3.19`

**Comment by gromenauer** [comment]
Works OK in `1.3.19` :+1: 

Collateral damage: Reload all when updating something downloaded with `manga-py` < `1.3.19`, but is not much price to pay.

**Comment by 1271** [comment]
:cry: Unfortunately, this is so for this provider
