### ISSUE TITLE
Bug. Provider freemanga.to

### ISSUE THREAD

**Issue by gromenauer** [yuru-yuri/manga-dl#96]
Tried in `manga-py` version `1.3.19`:

~~~ bash
pipenv run manga-py --cbz --zero-fill --rename-pages --destination Manga/ https://freemanga.to/manga/dusk-howler -c 1 --reverse-downloading
~~~

No image is downloaded into the `.cbz` file.

**Comment by 1271** [comment]
Thank you. I will check this.

**Comment by 1271** [comment]
As I see, the problem for the site:
https://freemanga.to/chapter/dusk-howler/chapter-86/b68f8.html

Images are broken.

Unfortunately, the current architecture of manga-py does not allow reporting an error when loading a file.

**Comment by gromenauer** [comment]
Thanks for looking into it.
Will search anywhere else when i read to this point.
