### ISSUE TITLE
Bug. Provider mangago.me

### ISSUE THREAD

**Issue by gromenauer** [yuru-yuri/manga-dl#97]
Tried in `manga-py` version `1.3.19`:

~~~ bash
pipenv run manga-py --cbz --zero-fill --rename-pages --destination Manga/ http://www.mangago.me/read-manga/feng_qi_cang_lan/
~~~

Nothing happens.
Maybe a Cloudflare thing? If so, please warn: "Cloudflare is ignoring you!!" :stuck_out_tongue_winking_eye: or something like that.

**Comment by 1271** [comment]
Thank you. Indeed, you need to print an error message.

I will check this.

**Comment by 1271** [comment]
It works for me.
Try to update the `cfscrape` package and your `nodejs`

For ubuntu:
```bash
~/: pip install -U cfscrape
~/: nvm install 10.8.0
~/: nvm use 10.8.0

~/: nove -v
v10.8.0
```

nvm: https://github.com/creationix/nvm

**Comment by gromenauer** [comment]
My `nodejs` seems ancient:
~~~
$ nodejs --version
v4.2.6
~~~
cfscrape is up to date.
Is it possible to warn of it from manga-py: "Warning: needs a newer version of nodejs"?

**Comment by 1271** [comment]
I'll try to do it the next time I update it :-)
